/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.gas.cliente.gui;

import Dados.ConectaBDProduto;
import Negocios.ClienteVasilhame;
import Negocios.ClienteVasilhameDetalhe;
import Negocios.Fachada;
import Negocios.Produto;
import Negocios.VendaDetalhe;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema.gas.cliente.dados.ConectaBDClienteVasilhame;
import sistema.gas.cliente.dados.ConectaBDClienteVasilhameDetalhe;

/**
 *
 * @author Heleno
 */
public class BaixaVasilhameClienteDialog extends javax.swing.JDialog {

    /**
     * Creates new form BaixaVasilhameClienteDialog
     *
     * @param parent
     * @param modal
     * @param clienteVasilhame
     */
    private final SimpleDateFormat fmtBrasilDataHora = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    private ClienteVasilhame clienteVasilhame;
    private VendaDetalhe vendaDetalhe;
    private Produto prodVasilhame;

    public BaixaVasilhameClienteDialog(java.awt.Frame parent, boolean modal, ClienteVasilhame clienteVasilhame) {
        super(parent, modal);
        try {
            initComponents();

            this.clienteVasilhame = clienteVasilhame;

            DefaultTableModel dtm = (DefaultTableModel) jT_detalhe.getModel();
            ArrayList<ClienteVasilhameDetalhe> listaClienteVasilhameDetalhe = ConectaBDClienteVasilhameDetalhe.getInstance().consultarClienteVasilhameDetalhe("select * from cliente_vasilhame_detalhe where id_cliente_vasilhame = " + clienteVasilhame.getId());
            for (ClienteVasilhameDetalhe clienteVasilhameDetalhe : listaClienteVasilhameDetalhe) {
                dtm.addRow(new Object[]{
                    fmtBrasilDataHora.format(clienteVasilhameDetalhe.getData_hora_transacao()),
                    clienteVasilhameDetalhe.getQuantidade_devolvida(),
                    true
                });
            }

            vendaDetalhe = Fachada.getInstancia().consultarVendaDetalhe_porIdVendaDetalhe(clienteVasilhame.getId_venda_detalhe());
            jTF_cod_produto.setText(vendaDetalhe.getProduto().getCodigo());
            jTF_desc_produto.setText(vendaDetalhe.getProduto().getDescricao());
            prodVasilhame = ConectaBDProduto.getInstance().consultarProduto_porId(clienteVasilhame.getId_produto_vasilhame());
            jTF_cod_produto_vasilhame.setText(prodVasilhame.getCodigo());
            jTF_desc_produto_vasilhame.setText(prodVasilhame.getDescricao());
            jTF_qtd_pendente.setText(clienteVasilhame.getQuantidade().setScale(2, RoundingMode.HALF_DOWN).toString());
            BigDecimal qtdTotalDevolvida = ConectaBDClienteVasilhameDetalhe.getInstance().consultarTotalDevolvidoClienteVasilhameDetalhe(clienteVasilhame.getId());
            jTF_qtd_devolvida.setText(qtdTotalDevolvida.setScale(2, RoundingMode.HALF_DOWN).toString());
            jTF_qtd_restante.setText(clienteVasilhame.getQuantidade().subtract(qtdTotalDevolvida).setScale(2, RoundingMode.HALF_DOWN).toString());
            jTF_qtd_a_devolver.setText("0.00");

            jB_add.setEnabled(!(clienteVasilhame.getQuantidade().subtract(qtdTotalDevolvida).setScale(2, RoundingMode.HALF_DOWN).compareTo(BigDecimal.ZERO) == 0));
            jB_confirmar.setEnabled(!(clienteVasilhame.getQuantidade().subtract(qtdTotalDevolvida).setScale(2, RoundingMode.HALF_DOWN).compareTo(BigDecimal.ZERO) == 0));

        } catch (SQLException ex) {
            Logger.getLogger(BaixaVasilhameClienteDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTF_cod_produto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_desc_produto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_cod_produto_vasilhame = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_desc_produto_vasilhame = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF_qtd_pendente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF_qtd_devolvida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTF_qtd_restante = new javax.swing.JTextField();
        jB_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_detalhe = new javax.swing.JTable();
        jB_confirmar = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTF_qtd_a_devolver = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Baixa de vasilhame");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Produto:");

        jTF_cod_produto.setEditable(false);

        jLabel2.setText("-");

        jTF_desc_produto.setEditable(false);

        jLabel3.setText("Vasilhame:");

        jTF_cod_produto_vasilhame.setEditable(false);

        jLabel4.setText("-");

        jTF_desc_produto_vasilhame.setEditable(false);

        jLabel5.setText("Qtd. vasilhame pendente:");

        jTF_qtd_pendente.setEditable(false);

        jLabel6.setText("Qtd. devolvida:");

        jTF_qtd_devolvida.setEditable(false);
        jTF_qtd_devolvida.setText("0.00");

        jLabel7.setText("Restante:");

        jTF_qtd_restante.setEditable(false);

        jB_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adiciona.png"))); // NOI18N
        jB_add.setText("Devolver");
        jB_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addActionPerformed(evt);
            }
        });

        jT_detalhe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Qtd. Devolvida", "banco?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_detalhe.getTableHeader().setReorderingAllowed(false);
        jT_detalhe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_detalheKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jT_detalhe);

        jB_confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoConfirmar.png"))); // NOI18N
        jB_confirmar.setText("Confirmar");
        jB_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_confirmarActionPerformed(evt);
            }
        });

        jB_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoCancelar.png"))); // NOI18N
        jB_cancelar.setText("Cancelar");
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Qtd. à devolver:");

        jTF_qtd_a_devolver.setText("0.00");
        jTF_qtd_a_devolver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_qtd_a_devolverFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jB_confirmar)
                .addGap(0, 0, 0)
                .addComponent(jB_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_qtd_a_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_add)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_qtd_pendente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_qtd_devolvida, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_qtd_restante, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTF_cod_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTF_cod_produto_vasilhame, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_desc_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                            .addComponent(jTF_desc_produto_vasilhame))))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_cancelar, jB_confirmar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTF_qtd_devolvida, jTF_qtd_pendente, jTF_qtd_restante});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_cod_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_desc_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_cod_produto_vasilhame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jTF_desc_produto_vasilhame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_qtd_pendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTF_qtd_devolvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTF_qtd_restante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_add)
                    .addComponent(jLabel8)
                    .addComponent(jTF_qtd_a_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_confirmar)
                    .addComponent(jB_cancelar))
                .addGap(5, 5, 5))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTF_qtd_devolvida, jTF_qtd_pendente, jTF_qtd_restante});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB_cancelar, jB_confirmar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addActionPerformed
        BigDecimal qtd_pendente = new BigDecimal(jTF_qtd_pendente.getText());
        BigDecimal qtd_restante = new BigDecimal(jTF_qtd_restante.getText());
        BigDecimal qtd_devolver = new BigDecimal(jTF_qtd_a_devolver.getText());
        BigDecimal qtd_devolvida = new BigDecimal(jTF_qtd_devolvida.getText());
        if ((qtd_devolver.compareTo(qtd_restante) <= 0) & !(qtd_devolver.compareTo(BigDecimal.ZERO) < 0) & !(qtd_devolver.compareTo(BigDecimal.ZERO) == 0)) {
            DefaultTableModel dtm = (DefaultTableModel) jT_detalhe.getModel();
            dtm.addRow(new Object[]{
                fmtBrasilDataHora.format(new Date()),
                qtd_devolver,
                false
            });
            qtd_devolvida = qtd_devolvida.add(qtd_devolver);
            qtd_restante = qtd_pendente.subtract(qtd_devolvida);
            jTF_qtd_devolvida.setText(qtd_devolvida.setScale(2, RoundingMode.HALF_DOWN).toString());
            jTF_qtd_restante.setText(qtd_restante.setScale(2, RoundingMode.HALF_DOWN).toString());

            if (qtd_restante.compareTo(BigDecimal.ZERO) == 0) {
                jB_add.setEnabled(false);
                clienteVasilhame.setStatus("Q");
            }
            jTF_qtd_a_devolver.setText("0.00");
        } else if (qtd_devolver.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(rootPane, "Números negativos não são válidos aqui!", "ALERTA DO SISTEMA", JOptionPane.WARNING_MESSAGE);
        } else if (qtd_devolver.compareTo(BigDecimal.ZERO) == 0) {
            JOptionPane.showMessageDialog(rootPane, "Zero não é um número válido aqui!", "ALERTA DO SISTEMA", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Quantidade superior a quantidade restante!", "ALERTA DO SISTEMA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jB_addActionPerformed

    private void jTF_qtd_a_devolverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_qtd_a_devolverFocusGained
        jTF_qtd_a_devolver.selectAll();
    }//GEN-LAST:event_jTF_qtd_a_devolverFocusGained

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jT_detalheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_detalheKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja excluir a devolução?", "PERGUNTA DO SISTEMA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                DefaultTableModel dtm = (DefaultTableModel) jT_detalhe.getModel();
                BigDecimal qtd_devolvida_detalhe = (BigDecimal) jT_detalhe.getModel().getValueAt(jT_detalhe.getSelectedRow(), 1);
                BigDecimal qtd_restante = new BigDecimal(jTF_qtd_restante.getText());
                BigDecimal qtd_devolvida = new BigDecimal(jTF_qtd_devolvida.getText());
                dtm.removeRow(jT_detalhe.getSelectedRow());
                qtd_devolvida = qtd_devolvida.subtract(qtd_devolvida_detalhe);
                qtd_restante = qtd_restante.add(qtd_devolvida_detalhe);
                jTF_qtd_devolvida.setText(qtd_devolvida.setScale(2, RoundingMode.HALF_DOWN).toString());
                jTF_qtd_restante.setText(qtd_restante.setScale(2, RoundingMode.HALF_DOWN).toString());
            }
        }
    }//GEN-LAST:event_jT_detalheKeyPressed

    private void jB_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_confirmarActionPerformed
        try {
            for (ClienteVasilhameDetalhe clienteVasilhameDetalhe : clienteVasilhame.getListaClienteVasilhameDetalhe()) {
                ConectaBDClienteVasilhameDetalhe.getInstance().excluirClienteVasilhameDetalheUnico(clienteVasilhameDetalhe);
            }

            for (int i = 0; i < jT_detalhe.getRowCount(); i++) {
                ClienteVasilhameDetalhe clienteVasilhameDetalhe = new ClienteVasilhameDetalhe();
                String dataHoraTabela = (String) jT_detalhe.getModel().getValueAt(i, 0);
                BigDecimal qtd_devolvida = (BigDecimal) jT_detalhe.getModel().getValueAt(i, 1);
                boolean banco = (Boolean) jT_detalhe.getModel().getValueAt(i, 2);
                Date datahora = fmtBrasilDataHora.parse(dataHoraTabela);
                clienteVasilhameDetalhe.setData_hora_transacao(datahora);
                clienteVasilhameDetalhe.setId_cliente_vasilhame(clienteVasilhame.getId());
                clienteVasilhameDetalhe.setQuantidade_devolvida(qtd_devolvida);
                ConectaBDClienteVasilhameDetalhe.getInstance().incluirClienteVasilhameDetalhe(clienteVasilhameDetalhe);
                if (!banco) {
                    ConectaBDProduto.getInstance().adicionarEstoqueProduto(qtd_devolvida, prodVasilhame);
                }
            }
            ConectaBDClienteVasilhame.getInstance().editaClienteVasilhame(clienteVasilhame);
            JOptionPane.showMessageDialog(rootPane, "salvo com sucesso!", "ALERTA DO SISTEMA", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(BaixaVasilhameClienteDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaixaVasilhameClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BaixaVasilhameClienteDialog dialog = new BaixaVasilhameClienteDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_add;
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_cod_produto;
    private javax.swing.JTextField jTF_cod_produto_vasilhame;
    private javax.swing.JTextField jTF_desc_produto;
    private javax.swing.JTextField jTF_desc_produto_vasilhame;
    private javax.swing.JTextField jTF_qtd_a_devolver;
    private javax.swing.JTextField jTF_qtd_devolvida;
    private javax.swing.JTextField jTF_qtd_pendente;
    private javax.swing.JTextField jTF_qtd_restante;
    private javax.swing.JTable jT_detalhe;
    // End of variables declaration//GEN-END:variables
}
