/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dados.ConectaBDConfiguracaoJurosParcelasReceber;
import Negocios.ConfiguracaoJurosParcelasReceber;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

/**
 *
 * @author Heleno
 */
public class ConfiguracaoJurosParcelasReceberDialog extends javax.swing.JDialog {

    /**
     * Creates new form ConfiguracaoJurosParcelasReceberDialog
     */
    private final ConectaBDConfiguracaoJurosParcelasReceber conexao = new ConectaBDConfiguracaoJurosParcelasReceber();
    private ConfiguracaoJurosParcelasReceber configuracaoJurosParcelasReceber;

    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ConfiguracaoJurosParcelasReceberDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(Utilitarios.Dir.imagens_internas + "icone.png"));

        configuracaoJurosParcelasReceber = conexao.retornaConfiguracaoJurosParcelasReceber(""
                + "select * from configuracao_juros_parcelas_receber where id = (select max(id) from configuracao_juros_parcelas_receber)");
        if (configuracaoJurosParcelasReceber != null) {
            if (configuracaoJurosParcelasReceber.getTipo_juros().equalsIgnoreCase("AA")) {
                jRB_aa.setSelected(true);
            } else if (configuracaoJurosParcelasReceber.getTipo_juros().equalsIgnoreCase("AM")) {
                jRB_am.setSelected(true);
            } else if (configuracaoJurosParcelasReceber.getTipo_juros().equalsIgnoreCase("AD")) {
                jRB_ad.setSelected(true);
            }
            BigDecimal cem = new BigDecimal(100);
            jTF_valor.setText(configuracaoJurosParcelasReceber.getValor_juros().multiply(cem).toString());
        } else {
            limparTela();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_opcao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRB_aa = new javax.swing.JRadioButton();
        jRB_am = new javax.swing.JRadioButton();
        jRB_ad = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTF_valor = new javax.swing.JTextField();
        jB_salvar = new javax.swing.JButton();
        jB_fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Juros Parcelas Receber");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Juros"));
        jPanel2.setFocusable(false);

        buttonGroup_opcao.add(jRB_aa);
        jRB_aa.setText("AA");
        jRB_aa.setToolTipText("Juros ao ano");
        jRB_aa.setFocusable(false);

        buttonGroup_opcao.add(jRB_am);
        jRB_am.setText("AM");
        jRB_am.setToolTipText("Juros ao mês");
        jRB_am.setFocusable(false);

        buttonGroup_opcao.add(jRB_ad);
        jRB_ad.setText("AD");
        jRB_ad.setToolTipText("Juros ao dia");
        jRB_ad.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jRB_aa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRB_am)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRB_ad)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB_aa)
                    .addComponent(jRB_am)
                    .addComponent(jRB_ad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Valor(%):");

        jTF_valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_valorFocusGained(evt);
            }
        });

        jB_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adiciona.png"))); // NOI18N
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jB_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoCancelar.png"))); // NOI18N
        jB_fechar.setText("Fechar");
        jB_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_salvar)
                        .addGap(0, 0, 0)
                        .addComponent(jB_fechar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTF_valor))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_salvar)
                    .addComponent(jB_fechar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 225, 201);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_jB_fecharActionPerformed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        try {
            boolean salvar;
            if (configuracaoJurosParcelasReceber == null) {
                configuracaoJurosParcelasReceber = new ConfiguracaoJurosParcelasReceber();
                salvar = true;
            } else {
                salvar = false;
            }
            jRB_aa.setActionCommand("AA");
            jRB_ad.setActionCommand("AD");
            jRB_am.setActionCommand("AM");
            configuracaoJurosParcelasReceber.setTipo_juros(buttonGroup_opcao.getSelection().getActionCommand());
            BigDecimal juros = new BigDecimal(jTF_valor.getText());
            BigDecimal cem = new BigDecimal(100);
            configuracaoJurosParcelasReceber.setValor_juros(juros.divide(cem).setScale(6, RoundingMode.HALF_DOWN));
            if (salvar) {
                conexao.incluirConfiguracaoJurosParcelasReceber(configuracaoJurosParcelasReceber);
                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!", "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                conexao.editarConfiguracaoJurosParcelasReceber(configuracaoJurosParcelasReceber);
                JOptionPane.showMessageDialog(rootPane, "Editado com sucesso!", "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao realizar operação!", "Alerta do Sistema", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jB_salvarActionPerformed

    private void jTF_valorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_valorFocusGained
        jTF_valor.selectAll();
    }//GEN-LAST:event_jTF_valorFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoJurosParcelasReceberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ConfiguracaoJurosParcelasReceberDialog dialog = new ConfiguracaoJurosParcelasReceberDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_opcao;
    private javax.swing.JButton jB_fechar;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRB_aa;
    private javax.swing.JRadioButton jRB_ad;
    private javax.swing.JRadioButton jRB_am;
    private javax.swing.JTextField jTF_valor;
    // End of variables declaration//GEN-END:variables

    private void limparTela() {
        jRB_aa.setSelected(true);
        jTF_valor.setText("0.00");
    }
}
