/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author Administrador
 */
public class DavAcrescimoDialogGUI extends javax.swing.JDialog {
    /**
     * Creates new form DavDescontoDialogGUI
     * @param parent
     * @param modal
     */
    public DavAcrescimoDialogGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jRB_desconto_taxa.setSelected(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(Utilitarios.Dir.imagens_internas + "icone.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRB_desconto_valor = new javax.swing.JRadioButton();
        jRB_desconto_taxa = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jTF_desconto = new javax.swing.JTextField();
        jB_ok = new javax.swing.JButton();
        jB_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acréscimo DAV");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Acréscimo"));
        jPanel1.setFocusable(false);

        buttonGroup1.add(jRB_desconto_valor);
        jRB_desconto_valor.setText("Acréscimo Valor(R$)");
        jRB_desconto_valor.setFocusable(false);

        buttonGroup1.add(jRB_desconto_taxa);
        jRB_desconto_taxa.setText("Acréscimo Taxa(%)");
        jRB_desconto_taxa.setFocusable(false);

        jLabel15.setText("Acréscimo");

        jTF_desconto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTF_desconto.setForeground(new java.awt.Color(0, 153, 0));
        jTF_desconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_desconto.setText("0.00");
        jTF_desconto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTF_desconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_descontoFocusGained(evt);
            }
        });
        jTF_desconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_descontoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB_desconto_valor)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTF_desconto))
                        .addComponent(jRB_desconto_taxa, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRB_desconto_valor)
                .addGap(18, 18, 18)
                .addComponent(jRB_desconto_taxa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTF_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jB_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jB_ok.setText("OK");
        jB_ok.setBorderPainted(false);
        jB_ok.setContentAreaFilled(false);
        jB_ok.setFocusable(false);
        jB_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB_okMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB_okMouseEntered(evt);
            }
        });
        jB_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_okActionPerformed(evt);
            }
        });

        jB_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jB_sair.setText("SAIR");
        jB_sair.setBorderPainted(false);
        jB_sair.setContentAreaFilled(false);
        jB_sair.setFocusable(false);
        jB_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB_sairMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB_sairMouseEntered(evt);
            }
        });
        jB_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jB_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_sair)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_ok)
                    .addComponent(jB_sair))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(248, 241));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_okMouseEntered
        jB_ok.setContentAreaFilled(true);
    }//GEN-LAST:event_jB_okMouseEntered

    private void jB_okMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_okMouseExited
        jB_ok.setContentAreaFilled(false);
    }//GEN-LAST:event_jB_okMouseExited

    private void jB_sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_sairMouseEntered
        jB_sair.setContentAreaFilled(true);
    }//GEN-LAST:event_jB_sairMouseEntered

    private void jB_sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_sairMouseExited
        jB_sair.setContentAreaFilled(false);
    }//GEN-LAST:event_jB_sairMouseExited

    private void jB_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_okActionPerformed
        dispose();
    }//GEN-LAST:event_jB_okActionPerformed

    private void jB_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sairActionPerformed
        dispose();
    }//GEN-LAST:event_jB_sairActionPerformed

    private void jTF_descontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_descontoFocusGained
        jTF_desconto.selectAll();
    }//GEN-LAST:event_jTF_descontoFocusGained

    private void jTF_descontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_descontoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_jTF_descontoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DavAcrescimoDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                DavAcrescimoDialogGUI dialog = new DavAcrescimoDialogGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jB_ok;
    private javax.swing.JButton jB_sair;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRB_desconto_taxa;
    private javax.swing.JRadioButton jRB_desconto_valor;
    private javax.swing.JTextField jTF_desconto;
    // End of variables declaration//GEN-END:variables

    public String retornaTipoAcrescimo() {
        jRB_desconto_taxa.setActionCommand("P");
        jRB_desconto_valor.setActionCommand("V");
        return buttonGroup1.getSelection().getActionCommand();
    }

    public String retornaValorAcrescimo() {
        BigDecimal bigDecimal = new BigDecimal(jTF_desconto.getText());
        return String.valueOf(bigDecimal.setScale(2, RoundingMode.HALF_DOWN));
    }
}