/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Cliente;
import Negocios.Funcionario;
import Negocios.TipoPagamento;
import Negocios.VendaCabecalho;
import Negocios.VendaDetalhe;
import Utilitarios.ClasseUtilitaria;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neto
 */
public class DetalharVendaDialog extends javax.swing.JDialog {

    /**
     * Creates new form DetalharVendaDialog
     *
     * @param parent
     * @param modal
     * @param vendaCabecalho
     */
    public DetalharVendaDialog(java.awt.Frame parent, boolean modal, VendaCabecalho vendaCabecalho) {
        super(parent, modal);
        initComponents();

        DefaultTableModel dtm = (DefaultTableModel) jT_produtos.getModel();
        dtm.setRowCount(0);

        Cliente cliente = vendaCabecalho.getCliente();
        jTF_cod_cliente.setText(cliente.getId().toString());
        jTF_nome_cliente.setText(cliente.getNome());
        TipoPagamento tipoPagamento = vendaCabecalho.getTipoPagamento();
        jTF_cod_tipo_pagamento.setText(String.valueOf(tipoPagamento.getId()));
        jTF_descricao_tipo_pagamento.setText(tipoPagamento.getDescricao());
        Funcionario vendedor = vendaCabecalho.getVendedor();
        jTF_cod_vendedor.setText(vendedor.getId().toString());
        jTF_nome_vendedor.setText(vendedor.getNome());
        for (VendaDetalhe vd : vendaCabecalho.getListaDetalhe()) {
            dtm.addRow(new Object[]{
                vd.getProduto().getId(),
                vd.getProduto().getCodigo(),
                vd.getProduto().getDescricao(),
                ClasseUtilitaria.fmtBig(vd.getQuantidade(), 2),
                ClasseUtilitaria.fmtBig(vd.getValor_unitario(), 2),
                ClasseUtilitaria.fmtBig(vd.getValor_total(), 2),
                vd.isVasilhame_pendente(),
                ClasseUtilitaria.fmtBig(vd.getQtd_vasilhame_pendente(), 2)
            });
        }
        jTF_subTotal.setText(ClasseUtilitaria.fmtBig(vendaCabecalho.getSubtotal(), 2));
        jTF_total.setText(ClasseUtilitaria.fmtBig(vendaCabecalho.getTotal(), 2));
        jTF_acrescimo.setText(ClasseUtilitaria.fmtBig(vendaCabecalho.getAcrescimo(), 2));
        jTF_desconto.setText(ClasseUtilitaria.fmtBig(vendaCabecalho.getDesconto(), 2));
        jL_tipoAcres.setText(vendaCabecalho.getTipo_acrescimo());
        jL_tipoDesconto.setText(vendaCabecalho.getTipo_desconto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_cadastrar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_produtos = new javax.swing.JTable();
        jTF_total = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTF_desconto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTF_subTotal = new javax.swing.JTextField();
        jL_tipoDesconto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTF_acrescimo = new javax.swing.JTextField();
        jL_tipoAcres = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_cod_cliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTF_nome_cliente = new javax.swing.JTextField();
        labelTipoPagamento = new javax.swing.JLabel();
        jTF_cod_tipo_pagamento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTF_descricao_tipo_pagamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_cod_vendedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_nome_vendedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");

        jP_cadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_cadastrar.setFocusable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));

        jT_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Descrição", "Quantidade", "Valor Uni", "Total", "debito de vasilhame?", "Qtd. Vas. Pend."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_produtos.setToolTipText("Para editar item ( 2 clique ou [enter] )   ...  Para excluir [Delete]");
        jT_produtos.setName("Produtos"); // NOI18N
        jT_produtos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jT_produtos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jT_produtos);
        if (jT_produtos.getColumnModel().getColumnCount() > 0) {
            jT_produtos.getColumnModel().getColumn(0).setMinWidth(0);
            jT_produtos.getColumnModel().getColumn(0).setPreferredWidth(0);
            jT_produtos.getColumnModel().getColumn(0).setMaxWidth(0);
            jT_produtos.getColumnModel().getColumn(1).setPreferredWidth(80);
            jT_produtos.getColumnModel().getColumn(2).setPreferredWidth(300);
            jT_produtos.getColumnModel().getColumn(3).setPreferredWidth(100);
            jT_produtos.getColumnModel().getColumn(4).setPreferredWidth(100);
            jT_produtos.getColumnModel().getColumn(5).setPreferredWidth(100);
            jT_produtos.getColumnModel().getColumn(6).setMinWidth(0);
            jT_produtos.getColumnModel().getColumn(6).setPreferredWidth(0);
            jT_produtos.getColumnModel().getColumn(6).setMaxWidth(0);
            jT_produtos.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        jTF_total.setEditable(false);
        jTF_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTF_total.setForeground(new java.awt.Color(0, 0, 255));
        jTF_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_total.setFocusable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Total:");

        jLabel15.setText("Desconto:");

        jTF_desconto.setEditable(false);
        jTF_desconto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTF_desconto.setForeground(new java.awt.Color(0, 153, 0));
        jTF_desconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_desconto.setText("0.00");
        jTF_desconto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setText("SubTotal:");

        jTF_subTotal.setEditable(false);
        jTF_subTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTF_subTotal.setForeground(new java.awt.Color(255, 0, 51));
        jTF_subTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_subTotal.setFocusable(false);

        jLabel1.setText("Acrescimo:");

        jTF_acrescimo.setEditable(false);
        jTF_acrescimo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTF_acrescimo.setForeground(new java.awt.Color(0, 153, 0));
        jTF_acrescimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_acrescimo.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_acrescimo)
                            .addComponent(jTF_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_tipoAcres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_tipoDesconto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel19))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_total)
                            .addComponent(jTF_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addComponent(jL_tipoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_tipoAcres, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_acrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTF_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTF_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Cliente:");

        jTF_cod_cliente.setEditable(false);
        jTF_cod_cliente.setName("Cliente"); // NOI18N

        jLabel8.setText("-");

        jTF_nome_cliente.setEditable(false);

        labelTipoPagamento.setText("Tipo Pagamento:");

        jTF_cod_tipo_pagamento.setEditable(false);
        jTF_cod_tipo_pagamento.setToolTipText("Pressione F1 para buscar o tipo de pagamento");
        jTF_cod_tipo_pagamento.setName("Tipo de Pagamento"); // NOI18N

        jLabel9.setText("-");

        jTF_descricao_tipo_pagamento.setEditable(false);

        jLabel2.setText("Vendedor:");

        jTF_cod_vendedor.setEditable(false);
        jTF_cod_vendedor.setName("Vendedor"); // NOI18N

        jLabel4.setText("-");

        jTF_nome_vendedor.setEditable(false);

        javax.swing.GroupLayout jP_cadastrarLayout = new javax.swing.GroupLayout(jP_cadastrar);
        jP_cadastrar.setLayout(jP_cadastrarLayout);
        jP_cadastrarLayout.setHorizontalGroup(
            jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP_cadastrarLayout.createSequentialGroup()
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTipoPagamento)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_cod_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTF_cod_tipo_pagamento)
                            .addComponent(jTF_cod_vendedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_nome_cliente))
                            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_descricao_tipo_pagamento))
                            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_nome_vendedor)))))
                .addContainerGap())
        );
        jP_cadastrarLayout.setVerticalGroup(
            jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_cod_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTF_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoPagamento)
                    .addComponent(jTF_cod_tipo_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTF_descricao_tipo_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_cod_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTF_nome_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jP_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalharVendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DetalharVendaDialog dialog = new DetalharVendaDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_tipoAcres;
    private javax.swing.JLabel jL_tipoDesconto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP_cadastrar;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTF_acrescimo;
    private javax.swing.JTextField jTF_cod_cliente;
    private javax.swing.JTextField jTF_cod_tipo_pagamento;
    private javax.swing.JTextField jTF_cod_vendedor;
    private javax.swing.JTextField jTF_desconto;
    private javax.swing.JTextField jTF_descricao_tipo_pagamento;
    private javax.swing.JTextField jTF_nome_cliente;
    private javax.swing.JTextField jTF_nome_vendedor;
    private javax.swing.JTextField jTF_subTotal;
    private javax.swing.JTextField jTF_total;
    private javax.swing.JTable jT_produtos;
    private javax.swing.JLabel labelTipoPagamento;
    // End of variables declaration//GEN-END:variables
}
