/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.FinanceiroParcelas;
import Utilitarios.ClasseUtilitaria;
import java.awt.FontMetrics;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import sistema.gas.financeiro.tableModel.EditarValorFinanceiroColumnModel;
import sistema.gas.financeiro.tableModel.TableModelEditarValorFinanceiro;

/**
 *
 * @author Heleno
 */
public class EditaValorVencimentoParcelasReceberDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditaValorVencimentoParcelasReceberDialog
     */
    private boolean cancelou;
    private final boolean contemParcelaPaga;
    private TableModelEditarValorFinanceiro model;

    public EditaValorVencimentoParcelasReceberDialog(java.awt.Frame parent, boolean modal, ArrayList<FinanceiroParcelas> arrayList,
            BigDecimal total, BigDecimal entrada, boolean contemParcelaPaga) {
        super(parent, modal);
        this.contemParcelaPaga = contemParcelaPaga;
        initComponents();
        configurarTableModel();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(Utilitarios.Dir.imagens_internas + "icone.png"));

        for (FinanceiroParcelas p : arrayList) {
            if (!p.getParcela().equals("ENTRADA")) {
                model.addRow(p);
            }
        }
        jTF_total.setText(ClasseUtilitaria.fmtBig(total, 2));
        jTF_entrada.setText(ClasseUtilitaria.fmtBig(entrada, 2));
        jTF_restante.setText("0,00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtParcelas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_total = new javax.swing.JTextField();
        jTF_entrada = new javax.swing.JTextField();
        jTF_restante = new javax.swing.JTextField();
        jB_confirmar = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vencimento", "Valor", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtParcelasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtParcelas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Total:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Entrada:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Restante:");

        jTF_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTF_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_total.setText("0,00");
        jTF_total.setEnabled(false);

        jTF_entrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTF_entrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_entrada.setText("0,00");
        jTF_entrada.setEnabled(false);

        jTF_restante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTF_restante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_restante.setText("0,00");
        jTF_restante.setEnabled(false);

        jB_confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoConfirmar.png"))); // NOI18N
        jB_confirmar.setText("Confirmar");
        jB_confirmar.setEnabled(false);
        jB_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_confirmarActionPerformed(evt);
            }
        });

        jB_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoCancelar.png"))); // NOI18N
        jB_cancelar.setText("Cancelar");
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_total, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jTF_entrada)
                            .addComponent(jTF_restante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jB_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_confirmar)
                        .addGap(0, 0, 0)
                        .addComponent(jB_cancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTF_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTF_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTF_restante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtParcelasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtParcelasKeyReleased
        BigDecimal decimalTotalParcelas = ClasseUtilitaria.parseToBig(jTF_total.getText());
        BigDecimal decimalEntrada = ClasseUtilitaria.parseToBig(jTF_entrada.getText());
        jTF_restante.setText(ClasseUtilitaria.fmtBig(decimalTotalParcelas.subtract(model.getTotalParcelas().add(decimalEntrada)), 2));

        if (ClasseUtilitaria.parseToBig(jTF_restante.getText()).compareTo(BigDecimal.ZERO) == 0 && !contemParcelaPaga) {
            jB_confirmar.setEnabled(true);
        } else {
            jB_confirmar.setEnabled(false);
        }
    }//GEN-LAST:event_jtParcelasKeyReleased

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        dispose();
        cancelou = true;
    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jB_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_confirmarActionPerformed
        dispose();
        cancelou = false;
    }//GEN-LAST:event_jB_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditaValorVencimentoParcelasReceberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditaValorVencimentoParcelasReceberDialog dialog = new EditaValorVencimentoParcelasReceberDialog(new javax.swing.JFrame(), true, null, BigDecimal.ZERO, BigDecimal.ZERO, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_entrada;
    private javax.swing.JTextField jTF_restante;
    private javax.swing.JTextField jTF_total;
    private javax.swing.JTable jtParcelas;
    // End of variables declaration//GEN-END:variables

    public ArrayList<FinanceiroParcelas> importaListaParcelas() {
        if (cancelou) {
            return null;
        } else {
            return (ArrayList<FinanceiroParcelas>) model.getDataSet();
        }
    }

    public double importaEntrada() {
        if (cancelou) {
            return 0;
        } else {
            return Double.parseDouble(jTF_entrada.getText());
        }
    }

    private void configurarTableModel() {
        jtParcelas.setModel(new TableModelEditarValorFinanceiro(jtParcelas));
        jtParcelas.setSelectionModel(new DefaultListSelectionModel() {

            @Override
            public String toString() {
                return "gridEditarValorFinanceiro";
            }
        });

        jtParcelas.setAutoCreateColumnsFromModel(false);
        jtParcelas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        FontMetrics fm = jtParcelas.getFontMetrics(jtParcelas.getFont());
        jtParcelas.setColumnModel(new EditarValorFinanceiroColumnModel(fm));
        jtParcelas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        model = (TableModelEditarValorFinanceiro) jtParcelas.getModel();
    }
}
