/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dados.ConectaBDProduto;
import Negocios.Fachada;
import Negocios.Fornecedor;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class FornecedorDialog extends javax.swing.JDialog {

    /**
     * Creates new form GrupoDialogGUI
     */
    private final boolean consultar;
    private Fornecedor fornecedor;

    public FornecedorDialog(java.awt.Frame parent, boolean modal, boolean consultar) {
        super(parent, modal);
        initComponents();
        this.consultar = consultar;
        listarFornecedor("%");

        jT_grupo.getColumnModel().getColumn(0).setPreferredWidth(15);
        jT_grupo.getColumnModel().getColumn(1).setPreferredWidth(150);

        botaoSalvar(false);
        jB_editar.setEnabled(false);
        jB_excluir.setEnabled(false);
        jB_salvar.setEnabled(false);

        jTF_pesquisar.addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    listarFornecedor("%" + jTF_pesquisar.getText() + "%");
                } else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    if (jT_grupo.getRowCount() > 0) {
                        jT_grupo.addRowSelectionInterval(0, 0);
                        jT_grupo.requestFocus();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpPrincipal = new javax.swing.JTabbedPane();
        jpConsultar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_grupo = new javax.swing.JTable();
        jB_novo = new javax.swing.JButton();
        jB_OK = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();
        jTF_pesquisar = new org.jdesktop.swingx.JXSearchField();
        jpCadastrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTF_razao_social = new javax.swing.JTextField();
        jB_salvar = new javax.swing.JButton();
        jB_excluir = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jL_codigo = new javax.swing.JLabel();
        jB_excluir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");
        setResizable(false);

        jtpPrincipal.setEnabled(false);
        jtpPrincipal.setFocusable(false);

        jpConsultar.setFocusable(false);

        jT_grupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_grupoMouseClicked(evt);
            }
        });
        jT_grupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_grupoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jT_grupo);

        jB_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adiciona.png"))); // NOI18N
        jB_novo.setText("Novo");
        jB_novo.setFocusable(false);
        jB_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_novoActionPerformed(evt);
            }
        });

        jB_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jB_OK.setText("Seleção");
        jB_OK.setFocusable(false);
        jB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OKActionPerformed(evt);
            }
        });

        jB_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jB_cancelar.setText("Fechar");
        jB_cancelar.setFocusable(false);
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        jTF_pesquisar.setPrompt("Buscar");

        javax.swing.GroupLayout jpConsultarLayout = new javax.swing.GroupLayout(jpConsultar);
        jpConsultar.setLayout(jpConsultarLayout);
        jpConsultarLayout.setHorizontalGroup(
            jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jTF_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_novo)
                .addGap(0, 0, 0)
                .addComponent(jB_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jB_cancelar)
                .addGap(87, 87, 87))
        );

        jpConsultarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_OK, jB_cancelar, jB_novo});

        jpConsultarLayout.setVerticalGroup(
            jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTF_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_OK)
                    .addComponent(jB_cancelar))
                .addGap(5, 5, 5))
        );

        jpConsultarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB_OK, jB_cancelar, jB_novo});

        jtpPrincipal.addTab("Consultar", jpConsultar);

        jpCadastrar.setFocusable(false);

        jLabel3.setText("Razão Social:");

        jTF_razao_social.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_razao_socialKeyPressed(evt);
            }
        });

        jB_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk.png"))); // NOI18N
        jB_salvar.setText("Salvar");
        jB_salvar.setFocusable(false);
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jB_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bin_closed.png"))); // NOI18N
        jB_excluir.setText("Excluir");
        jB_excluir.setFocusable(false);
        jB_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_excluirActionPerformed(evt);
            }
        });

        jB_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wand.png"))); // NOI18N
        jB_editar.setText("Editar");
        jB_editar.setFocusable(false);
        jB_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Código:");

        jL_codigo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jL_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jB_excluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar[1].jpg"))); // NOI18N
        jB_excluir1.setText("Cancelar");
        jB_excluir1.setFocusable(false);
        jB_excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_excluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastrarLayout = new javax.swing.GroupLayout(jpCadastrar);
        jpCadastrar.setLayout(jpCadastrarLayout);
        jpCadastrarLayout.setHorizontalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpCadastrarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_razao_social)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_salvar)
                .addGap(0, 0, 0)
                .addComponent(jB_editar)
                .addGap(0, 0, 0)
                .addComponent(jB_excluir)
                .addGap(0, 0, 0)
                .addComponent(jB_excluir1)
                .addGap(38, 38, 38))
        );

        jpCadastrarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_editar, jB_excluir, jB_excluir1, jB_salvar});

        jpCadastrarLayout.setVerticalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_excluir)
                    .addComponent(jB_salvar)
                    .addComponent(jB_editar)
                    .addComponent(jB_excluir1))
                .addContainerGap())
        );

        jpCadastrarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB_editar, jB_excluir, jB_excluir1, jB_salvar});

        jtpPrincipal.addTab("Cadastrar", jpCadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPrincipal)
        );

        setSize(new java.awt.Dimension(478, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jT_grupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_grupoMouseClicked
        try {
            int id = (Integer) jT_grupo.getModel().getValueAt(jT_grupo.getSelectedRow(), 0);
            fornecedor = Fachada.getInstancia().consultarFornecedor(id);
            if (evt.getClickCount() == 2) {
                if (consultar) {
                    dispose();
                } else {
                    fornecedorSelecionado();
                    botaoSalvar(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FornecedorDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_grupoMouseClicked

    private void jB_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_novoActionPerformed
        jtpPrincipal.setSelectedIndex(1);
        limpar();
        botaoSalvar(true);
        jB_editar.setEnabled(false);
        jB_excluir.setEnabled(false);
    }//GEN-LAST:event_jB_novoActionPerformed

    private void jB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OKActionPerformed
        fornecedorSelecionado();
        botaoSalvar(false);
    }//GEN-LAST:event_jB_OKActionPerformed

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jTF_razao_socialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_razao_socialKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar();
        }
    }//GEN-LAST:event_jTF_razao_socialKeyPressed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        salvar();
    }//GEN-LAST:event_jB_salvarActionPerformed

    private void jB_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_excluirActionPerformed
        if (fornecedor != null) {
            try {
                ArrayList listProdutos = ConectaBDProduto.getInstance().consultarProduto("SELECT * FROM produto WHERE id_fornecedor = " + fornecedor.getId());
                if (!listProdutos.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Há produtos cadastrados referenciando este Fornecedor! Exclusão não permitida!");
                } else {
                    Object[] options = {"Sim!", "Não!"};
                    int n = JOptionPane.showOptionDialog(
                            this, "Deseja excluir o Fornecedor?", "Pergunta do Sistema", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                            null, options, options[1]);
                    if (n == 0) {
                        try {
                            fornecedor.setExcluido(true);
                            Fachada.getInstancia().editarFornecedor(fornecedor);
                            JOptionPane.showMessageDialog(null, "FORNECEDOR EXCLUÍDO COM SUCESSO!");
                            limpar();
                            limparTabela();
                            listarFornecedor("%");
                            jtpPrincipal.setSelectedComponent(jpConsultar);
                        } catch (HeadlessException e) {
                            JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL EXCLUIR O FORNECEDOR!");
                            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "<null>", e);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(FornecedorDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jB_excluirActionPerformed

    private void jB_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarActionPerformed
        if (fornecedor != null) {
            fornecedor.setRazao_social(jTF_razao_social.getText());
            fornecedor.setExcluido(false);
            try {
                Fachada.getInstancia().editarFornecedor(fornecedor);
                JOptionPane.showMessageDialog(null, "FORNECEDOR EDITADO COM SUCESSO!",
                        "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE, null);
                limpar();
                listarFornecedor("%");
                jtpPrincipal.setSelectedComponent(jpConsultar);
                fornecedor = null;
            } catch (HeadlessException e) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "<null>", e);
                JOptionPane.showMessageDialog(null, "NÃO FOI POSSIVEL EDITAR O FORNECEDOR!",
                        "Alerta do Sistema", JOptionPane.ERROR_MESSAGE, null);
            } catch (SQLException ex) {
                Logger.getLogger(FornecedorDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jB_editarActionPerformed

    private void jT_grupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_grupoKeyPressed
        try {
            int id = (Integer) jT_grupo.getModel().getValueAt(jT_grupo.getSelectedRow(), 0);
            fornecedor = Fachada.getInstancia().consultarFornecedor(id);
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (consultar) {
                    dispose();
                } else {
                    fornecedorSelecionado();
                    botaoSalvar(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FornecedorDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_grupoKeyPressed

    private void jB_excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_excluir1ActionPerformed
        jtpPrincipal.setSelectedComponent(jpConsultar);
    }//GEN-LAST:event_jB_excluir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                FornecedorDialog dialog = new FornecedorDialog(new javax.swing.JFrame(), true, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_OK;
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_editar;
    private javax.swing.JButton jB_excluir;
    private javax.swing.JButton jB_excluir1;
    private javax.swing.JButton jB_novo;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JLabel jL_codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXSearchField jTF_pesquisar;
    private javax.swing.JTextField jTF_razao_social;
    private javax.swing.JTable jT_grupo;
    private javax.swing.JPanel jpCadastrar;
    private javax.swing.JPanel jpConsultar;
    private javax.swing.JTabbedPane jtpPrincipal;
    // End of variables declaration//GEN-END:variables

    public void limparTabela() {
        DefaultTableModel tableData = (DefaultTableModel) jT_grupo.getModel();
        tableData.setRowCount(0);
        jT_grupo.setModel(tableData);
        jTF_pesquisar.requestFocus();
    }

    public final void listarFornecedor(String dado) {
        try {
            limparTabela();
            ArrayList<Fornecedor> lista = Fachada.getInstancia().consultarFornecedor("RAZAO_SOCIAL", "%");
            DefaultTableModel dtm = (DefaultTableModel) jT_grupo.getModel();
            for (Fornecedor gTemp : lista) {
                dtm.addRow(new Object[]{gTemp.getId(), gTemp.getRazao_social()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(FornecedorDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public final void botaoSalvar(boolean b) {
        jB_salvar.setEnabled(b);
    }

    private void fornecedorSelecionado() {
        jB_editar.setEnabled(true);
        jB_excluir.setEnabled(true);
        int i = jT_grupo.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "NENHUM FORNECEDOR SELECIONADO!",
                    "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE, null);
        } else {
            jTF_razao_social.setText(fornecedor.getRazao_social());
            jL_codigo.setText(String.valueOf(fornecedor.getId()));
            jtpPrincipal.setSelectedComponent(jpCadastrar);
            jpCadastrar.hasFocus();
        }
    }

    public void limpar() {
        jTF_razao_social.setText("");
        jL_codigo.setText("0");
    }

    private void salvar() {
        fornecedor = new Fornecedor();
        fornecedor.setRazao_social(jTF_razao_social.getText().toUpperCase());
        fornecedor.setExcluido(false);
        try {
            fornecedor = Fachada.getInstancia().incluirFornecedor(fornecedor);
            if (consultar) {
                fornecedor = Fachada.getInstancia().consultarFornecedor(fornecedor.getId());
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "FORNECEDOR SALVO COM SUCESSO!",
                        "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE, null);
                jTF_razao_social.setText("");
                listarFornecedor("%");
                jtpPrincipal.setSelectedComponent(jpConsultar);
            }
        } catch (HeadlessException e) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "<null>", e);
        } catch (SQLException ex) {
            Logger.getLogger(FornecedorDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void insereProdutoRapido() {
        limpar();
        jB_editar.setEnabled(false);
        jB_excluir.setEnabled(false);
        jB_salvar.setEnabled(true);
        jtpPrincipal.setSelectedComponent(jpCadastrar);
    }

    public Fornecedor getFornecedor() {
        return fornecedor;
    }
}
