package GUI;

import Negocios.Fachada;
import Negocios.Funcionario;
import java.awt.AWTKeyStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import org.jdesktop.swingx.JXSearchField;
import sistema.gas.SISTEMA_GAS;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Fhilippe
 */
public class FuncionariosDialog extends javax.swing.JDialog {

    private final String data_atual = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
    private Funcionario funcionario = null;
    private final boolean consultar;

    /**
     * Creates new form Funcionarios_Dialog
     *
     * @param parent
     * @param modal
     * @param consultar
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FuncionariosDialog(java.awt.Frame parent, boolean modal, boolean consultar) {
        super(parent, modal);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(Utilitarios.Dir.imagens_internas + "icone.png"));

        this.consultar = consultar;

        jTF_cep.setFormatterFactory(formato("*****-***"));
        jTF_cep.setFocusLostBehavior(JFormattedTextField.COMMIT);

        jTF_celular_funcionario.setFormatterFactory(formato("(##)####-####"));
        jTF_celular_funcionario.setFocusLostBehavior(JFormattedTextField.COMMIT);

        jTF_telefone_funcionario.setFormatterFactory(formato("(##)####-####"));
        jTF_telefone_funcionario.setFocusLostBehavior(JFormattedTextField.COMMIT);

        jTF_cpf.setFormatterFactory(formato("***.***.***-**"));
        jTF_cpf.setFocusLostBehavior(JFormattedTextField.COMMIT);

        pesquisar();
        limparCampos();
        botoes(false, false, false);

        HashSet conj = new HashSet(jP_cadastrar.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        jP_dados_gerais.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
        jP_doc_obs_operador.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

        action();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_filtro = new javax.swing.ButtonGroup();
        buttonGroup_nivel_permissao = new javax.swing.ButtonGroup();
        jTP_funcionarios = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_lista_funcionarios = new javax.swing.JTable();
        jB_novo = new javax.swing.JButton();
        jB_ok = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();
        jTF_pesquisar = new org.jdesktop.swingx.JXSearchField();
        jcbMunicipio = new javax.swing.JRadioButton();
        jcbCpf = new javax.swing.JRadioButton();
        jcbCodigo = new javax.swing.JRadioButton();
        jcbNome = new javax.swing.JRadioButton();
        jP_cadastrar = new javax.swing.JPanel();
        jL_codigo = new javax.swing.JLabel();
        jTF_id_funcionario = new javax.swing.JTextField();
        jB_salvar = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jB_excluir = new javax.swing.JButton();
        jB_voltar = new javax.swing.JButton();
        jP_usuario = new javax.swing.JPanel();
        jTF_login_funcionario = new javax.swing.JTextField();
        jL_login = new javax.swing.JLabel();
        jL_senha = new javax.swing.JLabel();
        jTF_senha_funcionario = new javax.swing.JPasswordField();
        jTF_data_cadastro = new javax.swing.JFormattedTextField();
        jTP_dados_funcionario = new javax.swing.JTabbedPane();
        jP_dados_gerais = new javax.swing.JPanel();
        jL_email = new javax.swing.JLabel();
        jTF_email_funcionario = new javax.swing.JTextField();
        jL_telefone = new javax.swing.JLabel();
        jL_celular = new javax.swing.JLabel();
        jTF_celular_funcionario = new javax.swing.JFormattedTextField();
        jTF_municipio_funcionario = new javax.swing.JTextField();
        jTF_estado = new javax.swing.JTextField();
        jB_municipio = new javax.swing.JButton();
        jTF_codigo_municipio_funcionario = new javax.swing.JTextField();
        jL_municipio = new javax.swing.JLabel();
        jL_contato = new javax.swing.JLabel();
        jTF_bairro_funcionario = new javax.swing.JTextField();
        jL_bairro = new javax.swing.JLabel();
        jL_complemento = new javax.swing.JLabel();
        jTF_complemento_funcionario = new javax.swing.JTextField();
        jTF_endereco_funcionario = new javax.swing.JTextField();
        jL_endereco = new javax.swing.JLabel();
        jL_nome = new javax.swing.JLabel();
        jTF_nome_funcionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF_numero_funcionario = new javax.swing.JTextField();
        jTF_telefone_funcionario = new javax.swing.JFormattedTextField();
        jTF_cep = new javax.swing.JFormattedTextField();
        jP_doc_obs_operador = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTF_cpf = new javax.swing.JFormattedTextField();
        jTF_rg = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTF_observacao_funcionario = new javax.swing.JTextArea();
        jL_observacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Funcionarios");
        setBounds(new java.awt.Rectangle(0, 0, 600, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTP_funcionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTP_funcionarios.setEnabled(false);
        jTP_funcionarios.setFocusable(false);

        jPanel1.setFocusable(false);

        jT_lista_funcionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Município"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_lista_funcionarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jT_lista_funcionarios.getTableHeader().setReorderingAllowed(false);
        jT_lista_funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_lista_funcionariosMouseClicked(evt);
            }
        });
        jT_lista_funcionarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_lista_funcionariosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jT_lista_funcionarios);
        if (jT_lista_funcionarios.getColumnModel().getColumnCount() > 0) {
            jT_lista_funcionarios.getColumnModel().getColumn(0).setResizable(false);
            jT_lista_funcionarios.getColumnModel().getColumn(0).setPreferredWidth(80);
            jT_lista_funcionarios.getColumnModel().getColumn(1).setResizable(false);
            jT_lista_funcionarios.getColumnModel().getColumn(1).setPreferredWidth(350);
            jT_lista_funcionarios.getColumnModel().getColumn(2).setResizable(false);
            jT_lista_funcionarios.getColumnModel().getColumn(2).setPreferredWidth(120);
            jT_lista_funcionarios.getColumnModel().getColumn(3).setResizable(false);
            jT_lista_funcionarios.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        jB_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adiciona.png"))); // NOI18N
        jB_novo.setText("Novo");
        jB_novo.setFocusable(false);
        jB_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_novoActionPerformed(evt);
            }
        });

        jB_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jB_ok.setText("Seleção");
        jB_ok.setFocusable(false);
        jB_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_okActionPerformed(evt);
            }
        });

        jB_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jB_cancelar.setText("Fechar");
        jB_cancelar.setFocusable(false);
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        jTF_pesquisar.setPrompt("Buscar");

        buttonGroup_filtro.add(jcbMunicipio);
        jcbMunicipio.setText("Município");
        jcbMunicipio.setFocusable(false);

        buttonGroup_filtro.add(jcbCpf);
        jcbCpf.setText("CPF");
        jcbCpf.setFocusable(false);

        buttonGroup_filtro.add(jcbCodigo);
        jcbCodigo.setSelected(true);
        jcbCodigo.setText("Código");
        jcbCodigo.setFocusable(false);

        buttonGroup_filtro.add(jcbNome);
        jcbNome.setText("Nome");
        jcbNome.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMunicipio)
                            .addComponent(jcbCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCpf)
                            .addComponent(jcbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jB_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jB_cancelar)
                .addGap(165, 165, 165))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_cancelar, jB_novo, jB_ok});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTF_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbCodigo)
                            .addComponent(jcbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbMunicipio)
                            .addComponent(jcbCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_novo)
                    .addComponent(jB_ok)
                    .addComponent(jB_cancelar))
                .addGap(113, 113, 113))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB_cancelar, jB_novo, jB_ok});

        jTP_funcionarios.addTab("Consultar", jPanel1);

        jP_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jP_cadastrar.setFocusable(false);

        jL_codigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_codigo.setForeground(new java.awt.Color(0, 0, 153));
        jL_codigo.setText("CÓDIGO:");

        jTF_id_funcionario.setEditable(false);
        jTF_id_funcionario.setFocusable(false);

        jB_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk.png"))); // NOI18N
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jB_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wand.png"))); // NOI18N
        jB_editar.setText("Editar");
        jB_editar.setPreferredSize(new java.awt.Dimension(97, 25));
        jB_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarActionPerformed(evt);
            }
        });

        jB_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bin_closed.png"))); // NOI18N
        jB_excluir.setText("Excluir");
        jB_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_excluirActionPerformed(evt);
            }
        });

        jB_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jB_voltar.setText("Voltar");
        jB_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarActionPerformed(evt);
            }
        });

        jP_usuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de Usuário"));

        jTF_login_funcionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_login_funcionarioFocusLost(evt);
            }
        });

        jL_login.setText("LOGIN:");

        jL_senha.setText("SENHA:");

        javax.swing.GroupLayout jP_usuarioLayout = new javax.swing.GroupLayout(jP_usuario);
        jP_usuario.setLayout(jP_usuarioLayout);
        jP_usuarioLayout.setHorizontalGroup(
            jP_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_login_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jL_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_senha_funcionario)
                .addContainerGap())
        );
        jP_usuarioLayout.setVerticalGroup(
            jP_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_usuarioLayout.createSequentialGroup()
                .addGroup(jP_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_senha_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jL_senha))
                    .addGroup(jP_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_login_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jL_login)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jTF_data_cadastro.setEditable(false);
        jTF_data_cadastro.setFocusable(false);

        jTP_dados_funcionario.setFocusable(false);

        jP_dados_gerais.setFocusable(false);

        jL_email.setText("Email:");

        jL_telefone.setText("Telefone:");

        jL_celular.setText("Celular:");

        jTF_municipio_funcionario.setEditable(false);
        jTF_municipio_funcionario.setEnabled(false);

        jTF_estado.setEditable(false);
        jTF_estado.setEnabled(false);

        jB_municipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adiciona.png"))); // NOI18N
        jB_municipio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jB_municipio.setBorderPainted(false);
        jB_municipio.setContentAreaFilled(false);
        jB_municipio.setFocusable(false);
        jB_municipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB_municipioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB_municipioMouseExited(evt);
            }
        });
        jB_municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_municipioActionPerformed(evt);
            }
        });

        jTF_codigo_municipio_funcionario.setEditable(false);

        jL_municipio.setText("Município:");

        jL_contato.setText("CEP:");

        jL_bairro.setText("Bairro:");

        jL_complemento.setText("Complemento:");

        jL_endereco.setText("Endereço:");

        jL_nome.setText("Nome:");

        jLabel5.setText("Nº:");

        javax.swing.GroupLayout jP_dados_geraisLayout = new javax.swing.GroupLayout(jP_dados_gerais);
        jP_dados_gerais.setLayout(jP_dados_geraisLayout);
        jP_dados_geraisLayout.setHorizontalGroup(
            jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_dados_geraisLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_email)
                    .addComponent(jL_telefone)
                    .addComponent(jL_municipio)
                    .addComponent(jL_contato)
                    .addComponent(jL_bairro)
                    .addComponent(jL_complemento)
                    .addComponent(jL_endereco)
                    .addComponent(jL_nome))
                .addGap(0, 0, 0)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_dados_geraisLayout.createSequentialGroup()
                        .addComponent(jTF_endereco_funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_numero_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTF_complemento_funcionario)
                    .addComponent(jTF_bairro_funcionario)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_dados_geraisLayout.createSequentialGroup()
                        .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_email_funcionario)
                            .addGroup(jP_dados_geraisLayout.createSequentialGroup()
                                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTF_telefone_funcionario)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_dados_geraisLayout.createSequentialGroup()
                                        .addComponent(jTF_codigo_municipio_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jP_dados_geraisLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_municipio_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTF_estado))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_dados_geraisLayout.createSequentialGroup()
                                        .addGap(235, 235, 235)
                                        .addComponent(jL_celular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_celular_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(1, 1, 1))
                    .addComponent(jTF_nome_funcionario)
                    .addGroup(jP_dados_geraisLayout.createSequentialGroup()
                        .addComponent(jTF_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_dados_geraisLayout.setVerticalGroup(
            jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_dados_geraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_nome)
                    .addComponent(jTF_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_endereco)
                    .addComponent(jTF_endereco_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_numero_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_complemento)
                    .addComponent(jTF_complemento_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_bairro)
                    .addComponent(jTF_bairro_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_contato)
                    .addComponent(jTF_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_codigo_municipio_funcionario)
                        .addComponent(jL_municipio))
                    .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_municipio_funcionario)
                        .addComponent(jTF_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jB_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_telefone)
                    .addComponent(jL_celular)
                    .addComponent(jTF_celular_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_telefone_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_dados_geraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_email)
                    .addComponent(jTF_email_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTP_dados_funcionario.addTab("Gerais", jP_dados_gerais);

        jP_doc_obs_operador.setFocusable(false);

        jLabel17.setText("CPF:");

        jTF_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_cpfFocusGained(evt);
            }
        });

        jLabel18.setText("RG:");

        jTF_observacao_funcionario.setColumns(20);
        jTF_observacao_funcionario.setRows(5);
        jScrollPane2.setViewportView(jTF_observacao_funcionario);

        jL_observacao.setText("Observação:");

        javax.swing.GroupLayout jP_doc_obs_operadorLayout = new javax.swing.GroupLayout(jP_doc_obs_operador);
        jP_doc_obs_operador.setLayout(jP_doc_obs_operadorLayout);
        jP_doc_obs_operadorLayout.setHorizontalGroup(
            jP_doc_obs_operadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_doc_obs_operadorLayout.createSequentialGroup()
                .addGroup(jP_doc_obs_operadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_doc_obs_operadorLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel17))
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_observacao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, 0)
                .addGroup(jP_doc_obs_operadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_doc_obs_operadorLayout.setVerticalGroup(
            jP_doc_obs_operadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_doc_obs_operadorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jP_doc_obs_operadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTF_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_doc_obs_operadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTF_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP_doc_obs_operadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_observacao))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTP_dados_funcionario.addTab("Documento/Obs", jP_doc_obs_operador);

        javax.swing.GroupLayout jP_cadastrarLayout = new javax.swing.GroupLayout(jP_cadastrar);
        jP_cadastrar.setLayout(jP_cadastrarLayout);
        jP_cadastrarLayout.setHorizontalGroup(
            jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTP_dados_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jP_cadastrarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jL_codigo)
                        .addGap(4, 4, 4)
                        .addComponent(jTF_id_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTF_data_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jP_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jB_salvar)
                .addGap(0, 0, 0)
                .addComponent(jB_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jB_excluir)
                .addGap(0, 0, 0)
                .addComponent(jB_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_cadastrarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_editar, jB_excluir, jB_salvar, jB_voltar});

        jP_cadastrarLayout.setVerticalGroup(
            jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cadastrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_codigo)
                    .addComponent(jTF_id_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_data_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTP_dados_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_salvar)
                    .addComponent(jB_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_voltar)
                    .addComponent(jB_excluir))
                .addGap(406, 406, 406))
        );

        jP_cadastrarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB_editar, jB_excluir, jB_salvar, jB_voltar});

        jTP_funcionarios.addTab("Cadastrar", jP_cadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTP_funcionarios)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTP_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 533, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(684, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_okActionPerformed
        funcionarioSelecionado();
    }//GEN-LAST:event_jB_okActionPerformed

    private void jB_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_excluirActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(null, "Excluir funcionário?", "Pergunta do Sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)
                    == JOptionPane.YES_OPTION) {
                funcionario.setData_exclusao(new Date());
                funcionario.setId_usuario_exclusao(SISTEMA_GAS._FuncionarioLogado.getId());
                Fachada.getInstancia().excluirFuncionario(funcionario);
                limparCampos();
                pesquisar();
                JOptionPane.showMessageDialog(rootPane, "Funcionário excluído com sucesso!", "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE);
                jTP_funcionarios.setSelectedIndex(0);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar funcionário! Erro:" + e.getMessage(), "Alerta do Sistema", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(FuncionariosDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_excluirActionPerformed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        if (jTF_login_funcionario.getBackground() == Color.yellow) {
            JOptionPane.showMessageDialog(null, "Login já utilizado, escolha outro.");
            jTF_login_funcionario.setBackground(Color.yellow);
            jTF_login_funcionario.requestFocus();
            jTF_login_funcionario.selectAll();
        } else {
            jTF_login_funcionario.setBackground(Color.white);
            try {
                funcionario = new Funcionario();
                funcionario.setBairro(jTF_bairro_funcionario.getText().toUpperCase().trim());
                funcionario.setCelular(jTF_celular_funcionario.getText().replaceAll("[^0-9]", ""));
                funcionario.setCodigo_municipio(jTF_codigo_municipio_funcionario.getText());
                funcionario.setComp_end(jTF_complemento_funcionario.getText().toUpperCase().trim());
                funcionario.setEmail(jTF_email_funcionario.getText());
                funcionario.setEndereco(jTF_endereco_funcionario.getText().toUpperCase().trim());
                funcionario.setUf(jTF_estado.getText());
                funcionario.setMunicipio(jTF_municipio_funcionario.getText().toUpperCase().trim());
                funcionario.setNome(jTF_nome_funcionario.getText().toUpperCase().trim());
                funcionario.setNum_end(jTF_numero_funcionario.getText());
                funcionario.setObs(jTF_observacao_funcionario.getText().toUpperCase().trim());
                funcionario.setTelefone(jTF_telefone_funcionario.getText().replaceAll("[^0-9]", ""));
                funcionario.setData_cadastro(new Date());
                funcionario.setCpf(jTF_cpf.getText().replaceAll("[^0-9]", ""));
                funcionario.setRg(jTF_rg.getText().replaceAll("[^0-9]", ""));
                funcionario.setUsuario(jTF_login_funcionario.getText());
                funcionario.setSenha(jTF_senha_funcionario.getText());
                funcionario.setId_usuario_insercao(SISTEMA_GAS._FuncionarioLogado != null ? SISTEMA_GAS._FuncionarioLogado.getId() : 1);
                funcionario.setCep(jTF_cep.getText().replaceAll("[^0-9]", ""));
                Fachada.getInstancia().incluirFuncionario(funcionario);
                if (consultar) {
                    dispose();
                } else {
                    limparCampos();
                    pesquisar();
                    JOptionPane.showMessageDialog(rootPane, "Funcionário salvo com sucesso!", "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE);
                    jTP_funcionarios.setSelectedIndex(0);
                }
            } catch (HeadlessException | NumberFormatException e) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "<null>", e);
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar funcionário! Erro:" + e.getMessage(), "Alerta do Sistema", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(FuncionariosDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jB_salvarActionPerformed

    private void jB_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_novoActionPerformed
        limparCampos();
        jTP_funcionarios.setSelectedIndex(1);
        jTP_dados_funcionario.setSelectedIndex(0);
        botoes(true, false, false);
    }//GEN-LAST:event_jB_novoActionPerformed

    private void jT_lista_funcionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_lista_funcionariosMouseClicked
        if (evt.getClickCount() == 2) {
            funcionarioSelecionado();
        }
    }//GEN-LAST:event_jT_lista_funcionariosMouseClicked

    private void jB_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarActionPerformed
        if (jTF_login_funcionario.getBackground() == Color.yellow) {
            JOptionPane.showMessageDialog(null, "Login já utilizado, escolha outro.");
            jTF_login_funcionario.setBackground(Color.yellow);
            jTF_login_funcionario.requestFocus();
            jTF_login_funcionario.selectAll();
        } else {
            jTF_login_funcionario.setBackground(Color.white);
            try {
                funcionario.setBairro(jTF_bairro_funcionario.getText().toUpperCase().trim());
                funcionario.setCelular(jTF_celular_funcionario.getText().replaceAll("[^0-9]", ""));
                funcionario.setCodigo_municipio(jTF_codigo_municipio_funcionario.getText());
                funcionario.setComp_end(jTF_complemento_funcionario.getText().toUpperCase().trim());
                funcionario.setEmail(jTF_email_funcionario.getText());
                funcionario.setEndereco(jTF_endereco_funcionario.getText().toUpperCase().trim());
                funcionario.setUf(jTF_estado.getText());
                funcionario.setMunicipio(jTF_municipio_funcionario.getText().toUpperCase().trim());
                funcionario.setNome(jTF_nome_funcionario.getText().toUpperCase().trim());
                funcionario.setNum_end(jTF_numero_funcionario.getText());
                funcionario.setObs(jTF_observacao_funcionario.getText().toUpperCase().trim());
                funcionario.setTelefone(jTF_telefone_funcionario.getText().replaceAll("[^0-9]", ""));
                funcionario.setData_cadastro(new Date());
                funcionario.setCpf(jTF_cpf.getText().replaceAll("[^0-9]", ""));
                funcionario.setRg(jTF_rg.getText().replaceAll("[^0-9]", ""));
                funcionario.setUsuario(jTF_login_funcionario.getText());
                funcionario.setSenha(jTF_senha_funcionario.getText());
                funcionario.setId_usuario_insercao(SISTEMA_GAS._FuncionarioLogado != null ? SISTEMA_GAS._FuncionarioLogado.getId() : 1);
                funcionario.setCep(jTF_cep.getText().replaceAll("[^0-9]", ""));
                try {
                    Fachada.getInstancia().editarFuncionario(funcionario);
                    if (consultar) {
                        dispose();
                    } else {
                        limparCampos();
                        pesquisar();
                        JOptionPane.showMessageDialog(rootPane, "Funcionário editado com sucesso!", "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE);
                        jTP_funcionarios.setSelectedIndex(0);
                    }
                } catch (HeadlessException e) {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao editar funcionário! Erro:" + e.getMessage(), "Alerta do Sistema", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception exception) {
                System.out.println(exception);
            }
        }
    }//GEN-LAST:event_jB_editarActionPerformed

    private void jB_municipioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_municipioMouseEntered
        jB_municipio.setContentAreaFilled(true);
    }//GEN-LAST:event_jB_municipioMouseEntered

    private void jB_municipioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_municipioMouseExited
        jB_municipio.setContentAreaFilled(false);
    }//GEN-LAST:event_jB_municipioMouseExited

    private void jB_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_municipioActionPerformed
        MunicipiosDialog municipiosDialog = new MunicipiosDialog(null, true);
        municipiosDialog.setLocationRelativeTo(null);
        municipiosDialog.setVisible(true);
        if (municipiosDialog.importarMunicipio() != null) {
            jTF_codigo_municipio_funcionario.setText(municipiosDialog.importarMunicipio().getCodigo_cidade());
            jTF_municipio_funcionario.setText(municipiosDialog.importarMunicipio().getNome());
            jTF_estado.setText(municipiosDialog.importarMunicipio().getUf());
            jTF_telefone_funcionario.requestFocus();
        }
    }//GEN-LAST:event_jB_municipioActionPerformed

    private void jTF_cpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_cpfFocusGained
        jTF_cpf.setFormatterFactory(formato("***.***.***-**"));
    }//GEN-LAST:event_jTF_cpfFocusGained

    private void jB_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarActionPerformed
        funcionario = null;
        limparCampos();
        pesquisar();
        jTP_funcionarios.setSelectedIndex(0);
    }//GEN-LAST:event_jB_voltarActionPerformed

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        funcionario = null;
        dispose();
    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jT_lista_funcionariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_lista_funcionariosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            funcionarioSelecionado();
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            jT_lista_funcionarios.clearSelection();
            jTF_pesquisar.requestFocus();
            jTF_pesquisar.selectAll();
        }
    }//GEN-LAST:event_jT_lista_funcionariosKeyPressed

    private void jTF_login_funcionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_login_funcionarioFocusLost

    }//GEN-LAST:event_jTF_login_funcionarioFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (jTP_funcionarios.getSelectedIndex() == 1) {
            funcionario = null;
            limparCampos();
            pesquisar();
            jTP_funcionarios.setSelectedIndex(0);
        } else {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionariosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FuncionariosDialog dialog = new FuncionariosDialog(new javax.swing.JFrame(), true, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_filtro;
    private javax.swing.ButtonGroup buttonGroup_nivel_permissao;
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_editar;
    private javax.swing.JButton jB_excluir;
    private javax.swing.JButton jB_municipio;
    private javax.swing.JButton jB_novo;
    private javax.swing.JButton jB_ok;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JLabel jL_bairro;
    private javax.swing.JLabel jL_celular;
    private javax.swing.JLabel jL_codigo;
    private javax.swing.JLabel jL_complemento;
    private javax.swing.JLabel jL_contato;
    private javax.swing.JLabel jL_email;
    private javax.swing.JLabel jL_endereco;
    private javax.swing.JLabel jL_login;
    private javax.swing.JLabel jL_municipio;
    private javax.swing.JLabel jL_nome;
    private javax.swing.JLabel jL_observacao;
    private javax.swing.JLabel jL_senha;
    private javax.swing.JLabel jL_telefone;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jP_cadastrar;
    private javax.swing.JPanel jP_dados_gerais;
    private javax.swing.JPanel jP_doc_obs_operador;
    private javax.swing.JPanel jP_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTF_bairro_funcionario;
    private javax.swing.JFormattedTextField jTF_celular_funcionario;
    private javax.swing.JFormattedTextField jTF_cep;
    private javax.swing.JTextField jTF_codigo_municipio_funcionario;
    private javax.swing.JTextField jTF_complemento_funcionario;
    private javax.swing.JFormattedTextField jTF_cpf;
    private javax.swing.JFormattedTextField jTF_data_cadastro;
    private javax.swing.JTextField jTF_email_funcionario;
    private javax.swing.JTextField jTF_endereco_funcionario;
    private javax.swing.JTextField jTF_estado;
    private javax.swing.JTextField jTF_id_funcionario;
    private javax.swing.JTextField jTF_login_funcionario;
    private javax.swing.JTextField jTF_municipio_funcionario;
    private javax.swing.JTextField jTF_nome_funcionario;
    private javax.swing.JTextField jTF_numero_funcionario;
    private javax.swing.JTextArea jTF_observacao_funcionario;
    private org.jdesktop.swingx.JXSearchField jTF_pesquisar;
    private javax.swing.JFormattedTextField jTF_rg;
    private javax.swing.JPasswordField jTF_senha_funcionario;
    private javax.swing.JFormattedTextField jTF_telefone_funcionario;
    private javax.swing.JTabbedPane jTP_dados_funcionario;
    private javax.swing.JTabbedPane jTP_funcionarios;
    private javax.swing.JTable jT_lista_funcionarios;
    private javax.swing.JRadioButton jcbCodigo;
    private javax.swing.JRadioButton jcbCpf;
    private javax.swing.JRadioButton jcbMunicipio;
    private javax.swing.JRadioButton jcbNome;
    // End of variables declaration//GEN-END:variables

    private void limparTabelaFuncionarios() {
        DefaultTableModel dtm = (DefaultTableModel) jT_lista_funcionarios.getModel();
        dtm.setRowCount(0);
    }

    private void limparCampos() {
        for (Component field : jP_dados_gerais.getComponents()) {
            if (field instanceof JTextField) {
                ((JTextField) field).setText("");
            }
            if (field instanceof JFormattedTextField) {
                ((JFormattedTextField) field).setText("");
            }
            if (field instanceof JRadioButton) {
                ((JRadioButton) field).setSelected(false);
            }
        }

        for (Component field : jP_usuario.getComponents()) {
            if (field instanceof JTextField) {
                ((JTextField) field).setText("");
            }
            if (field instanceof JFormattedTextField) {
                ((JFormattedTextField) field).setText("");
            }
        }

        for (Component field : jP_doc_obs_operador.getComponents()) {

            if (field instanceof JFormattedTextField) {
                ((JFormattedTextField) field).setText("");
            }

            if (field instanceof JTextArea) {
                ((JTextArea) field).setText("");
            }
        }
        jcbNome.setSelected(true);
        jTF_data_cadastro.setText(data_atual);
    }

    private void botoes(boolean s, boolean ed, boolean ex) {
        jB_salvar.setEnabled(s);
        jB_editar.setEnabled(ed);
        jB_excluir.setEnabled(ex);
    }

    private DefaultFormatterFactory formato(String mask) {
        MaskFormatter comFoco = null;
        try {
            comFoco = new MaskFormatter(mask);
            comFoco.setValidCharacters("0123456789"); // adicione os caracteres validos  
        } catch (ParseException pe) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "<null>", pe);
        }
        DefaultFormatterFactory factory = new DefaultFormatterFactory(comFoco, comFoco);
        return factory;
    }

    private void funcionarioSelecionado() {
        try {
            int row = jT_lista_funcionarios.getSelectedRow();
            if (row > -1) {
                int id_funcionario = (Integer) jT_lista_funcionarios.getModel().getValueAt(row, 0);
                ArrayList listaFuncionario = Fachada.getInstancia().consultarFuncionario("select * from funcionario where id = " + id_funcionario);
                funcionario = (Funcionario) listaFuncionario.get(0);
                if (consultar) {
                    dispose();
                } else {
                    jTF_id_funcionario.setText(String.valueOf(funcionario.getId()));
                    SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
                    String data_formatada = out.format(funcionario.getData_cadastro());
                    jTF_data_cadastro.setText(data_formatada);
                    jTF_nome_funcionario.setText(funcionario.getNome());
                    jTF_endereco_funcionario.setText(funcionario.getEndereco());
                    jTF_complemento_funcionario.setText(funcionario.getComp_end());
                    jTF_numero_funcionario.setText(funcionario.getNum_end());
                    jTF_bairro_funcionario.setText(funcionario.getBairro());
                    jTF_codigo_municipio_funcionario.setText(funcionario.getCodigo_municipio());
                    jTF_municipio_funcionario.setText(funcionario.getMunicipio());
                    jTF_cep.setText(funcionario.getCep());
                    jTF_estado.setText(funcionario.getUf());
                    jTF_telefone_funcionario.setText(funcionario.getTelefone());
                    jTF_celular_funcionario.setText(funcionario.getCelular());
                    jTF_email_funcionario.setText(funcionario.getEmail());
                    jTF_observacao_funcionario.setText(funcionario.getObs());
                    jTF_cpf.setText(funcionario.getCpf());
                    jTF_rg.setText(funcionario.getRg());

                    jTF_login_funcionario.setText(funcionario.getUsuario());
                    jTF_senha_funcionario.setText(funcionario.getSenha());
                    botoes(false, true, true);
                    jTP_funcionarios.setSelectedIndex(1);
                    jTP_dados_funcionario.setSelectedIndex(0);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nenhum funcionário selecionado!", "Alerta do Sistema", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(FuncionariosDialog.class.getName()).log(Level.SEVERE, "Falha no cadastro do Funcionario", ex);
            JOptionPane.showMessageDialog(rootPane, "Falha no cadastro do Funcionario" + "\n" + ex + "\n" + ex.getMessage());
        }
    }

    private void pesquisar() {
        try {
            jcbCpf.setActionCommand("cpf");
            jcbCodigo.setActionCommand("id");
            jcbMunicipio.setActionCommand("municipio");
            jcbNome.setActionCommand("nome");
            String busca = jTF_pesquisar.getText().isEmpty() ? "%" : jTF_pesquisar.getText();
            DefaultTableModel dtm = (DefaultTableModel) jT_lista_funcionarios.getModel();
            ArrayList<Funcionario> listaFuncionario = Fachada.getInstancia().consultarFuncionario("SELECT * FROM funcionario "
                    + "WHERE " + buttonGroup_filtro.getSelection().getActionCommand() + " LIKE '" + busca + "' "
                    + "AND NOT EXCLUIDO");
            limparTabelaFuncionarios();
            for (Funcionario f : listaFuncionario) {
                dtm.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getCpf(),
                    f.getMunicipio()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(FuncionariosDialog.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Falha consultar Funcionário" + "\n" + ex + "\n" + ex.getMessage());
        }
    }

    public Funcionario getFuncionario() {
        return funcionario;
    }

    private void action() {
        jTF_pesquisar.setSearchMode(JXSearchField.SearchMode.REGULAR);
        jTF_pesquisar.addKeyListener(new KeyAdapter() {
            public void KeyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    pesquisar();
                } else if (evt.getKeyCode() == KeyEvent.VK_DOWN
                        && jT_lista_funcionarios.getRowCount() > 0) {
                    jT_lista_funcionarios.addRowSelectionInterval(0, 0);
                    jT_lista_funcionarios.requestFocus();
                }
            }
        });
    }
}
