/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dados.ConectaBDProduto;
import Negocios.Fachada;
import Negocios.Grupo;
import Utilitarios.Dir;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class GrupoDialogGUI extends javax.swing.JDialog {

    /**
     * Creates new form GrupoDialogGUI
     */
    private Grupo grupo = new Grupo();
    private final boolean consultar;

    public GrupoDialogGUI(java.awt.Frame parent, boolean modal, boolean consultar) {
        super(parent, modal);
        initComponents();
        if (Dir.KEY_TIPO_SISTEMA.equals("G")) {
            jPanel2.setVisible(true);
        } else {
            jPanel2.setVisible(false);
        }
        this.consultar = consultar;
        listarGrupo();

        jT_grupo.getColumnModel().getColumn(0).setPreferredWidth(15);
        jT_grupo.getColumnModel().getColumn(1).setPreferredWidth(150);

        botaoSalvar(false);
        jB_editar.setEnabled(false);
        jB_excluir.setEnabled(false);
        jB_salvar.setEnabled(false);

        jTF_pesquisar.addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    pesquisar();
                } else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    if (jT_grupo.getRowCount() > 0) {
                        jT_grupo.addRowSelectionInterval(0, 0);
                        jT_grupo.requestFocus();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTP_grupo = new javax.swing.JTabbedPane();
        jP_consultar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_grupo = new javax.swing.JTable();
        jB_novo = new javax.swing.JButton();
        jB_OK = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();
        jTF_pesquisar = new org.jdesktop.swingx.JXSearchField();
        jP_cadastrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTF_descricao = new javax.swing.JTextField();
        jB_salvar = new javax.swing.JButton();
        jB_excluir = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jL_codigo = new javax.swing.JLabel();
        jB_excluir1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCB_vasilhames = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Grupo");
        setResizable(false);

        jTP_grupo.setEnabled(false);
        jTP_grupo.setFocusable(false);

        jP_consultar.setFocusable(false);

        jT_grupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_grupoMouseClicked(evt);
            }
        });
        jT_grupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_grupoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jT_grupo);

        jB_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adiciona.png"))); // NOI18N
        jB_novo.setText("Novo");
        jB_novo.setFocusable(false);
        jB_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_novoActionPerformed(evt);
            }
        });

        jB_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jB_OK.setText("Seleção");
        jB_OK.setFocusable(false);
        jB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OKActionPerformed(evt);
            }
        });

        jB_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jB_cancelar.setText("Fechar");
        jB_cancelar.setFocusable(false);
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        jTF_pesquisar.setPrompt("Buscar");

        javax.swing.GroupLayout jP_consultarLayout = new javax.swing.GroupLayout(jP_consultar);
        jP_consultar.setLayout(jP_consultarLayout);
        jP_consultarLayout.setHorizontalGroup(
            jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_consultarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jTF_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addGroup(jP_consultarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jB_novo)
                .addGap(0, 0, 0)
                .addComponent(jB_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jB_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_consultarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_OK, jB_cancelar, jB_novo});

        jP_consultarLayout.setVerticalGroup(
            jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_consultarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTF_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_OK)
                    .addComponent(jB_cancelar))
                .addGap(5, 5, 5))
        );

        jP_consultarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB_OK, jB_cancelar, jB_novo});

        jTP_grupo.addTab("Consultar", jP_consultar);

        jP_cadastrar.setFocusable(false);

        jLabel3.setText("Descrição:");

        jTF_descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_descricaoKeyPressed(evt);
            }
        });

        jB_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk.png"))); // NOI18N
        jB_salvar.setText("Salvar");
        jB_salvar.setFocusable(false);
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jB_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bin_closed.png"))); // NOI18N
        jB_excluir.setText("Excluir");
        jB_excluir.setFocusable(false);
        jB_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_excluirActionPerformed(evt);
            }
        });

        jB_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wand.png"))); // NOI18N
        jB_editar.setText("Editar");
        jB_editar.setFocusable(false);
        jB_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Código:");

        jL_codigo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jL_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jB_excluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar[1].jpg"))); // NOI18N
        jB_excluir1.setText("Cancelar");
        jB_excluir1.setFocusable(false);
        jB_excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_excluir1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de Vasilhame"));

        jCB_vasilhames.setText("Produtos deste grupo são vasilhames");
        jCB_vasilhames.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCB_vasilhames.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCB_vasilhames.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCB_vasilhames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCB_vasilhames)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jP_cadastrarLayout = new javax.swing.GroupLayout(jP_cadastrar);
        jP_cadastrar.setLayout(jP_cadastrarLayout);
        jP_cadastrarLayout.setHorizontalGroup(
            jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP_cadastrarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_descricao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cadastrarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB_salvar)
                        .addGap(0, 0, 0)
                        .addComponent(jB_editar)
                        .addGap(0, 0, 0)
                        .addComponent(jB_excluir)
                        .addGap(0, 0, 0)
                        .addComponent(jB_excluir1)
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );

        jP_cadastrarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_editar, jB_excluir, jB_excluir1, jB_salvar});

        jP_cadastrarLayout.setVerticalGroup(
            jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_excluir)
                    .addComponent(jB_salvar)
                    .addComponent(jB_editar)
                    .addComponent(jB_excluir1))
                .addContainerGap())
        );

        jP_cadastrarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB_editar, jB_excluir, jB_excluir1, jB_salvar});

        jTP_grupo.addTab("Cadastrar", jP_cadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTP_grupo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTP_grupo)
        );

        setSize(new java.awt.Dimension(479, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jT_grupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_grupoMouseClicked
        try {
            int id = (Integer) jT_grupo.getModel().getValueAt(jT_grupo.getSelectedRow(), 0);
            ArrayList lista = Fachada.getInstancia().consultarGrupo("select * from grupo where id = " + id + " and not excluido");
            grupo = (Grupo) lista.get(0);
            if (evt.getClickCount() == 2) {
                if (consultar) {
                    dispose();
                } else {
                    grupoSelecionado();
                    botaoSalvar(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrupoDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_grupoMouseClicked

    private void jB_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_novoActionPerformed
        jTP_grupo.add("Cadastrar", jP_cadastrar);
        jTP_grupo.setSelectedIndex(1);
        limpar();
        botaoSalvar(true);
        jB_editar.setEnabled(false);
        jB_excluir.setEnabled(false);
    }//GEN-LAST:event_jB_novoActionPerformed

    private void jB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OKActionPerformed
        grupoSelecionado();
        botaoSalvar(false);
    }//GEN-LAST:event_jB_OKActionPerformed

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jTF_descricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_descricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar();
        }
    }//GEN-LAST:event_jTF_descricaoKeyPressed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        salvar();
    }//GEN-LAST:event_jB_salvarActionPerformed

    private void jB_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_excluirActionPerformed
        if (grupo != null) {
            try {
                ArrayList listProdutos = ConectaBDProduto.getInstance().consultarProduto("SELECT * FROM produto WHERE id_grupo = " + grupo.getId());
                if (!listProdutos.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Há produtos cadastrados referenciando este grupo! Exclusão não permitida!");
                } else {
                    Object[] options = {"Sim!", "Não!"};
                    int n = JOptionPane.showOptionDialog(
                            this, "Deseja excluir o grupo?", "Pergunta do Sistema", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                            null, options, options[1]);
                    if (n == 0) {
                        try {
                            grupo.setData_exclusao(new Date());
                            grupo.setId_usuario_exclusao(1);
                            Fachada.getInstancia().alterarGrupoExclusao(grupo);
                            JOptionPane.showMessageDialog(null, "GRUPO EXCLUÍDO COM SUCESSO!");
                            limpar();
                            limparTabela();
                            listarGrupo();
                            jTP_grupo.remove(1);
                            jTP_grupo.setSelectedIndex(0);
                        } catch (HeadlessException e) {
                            JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL EXCLUIR O GRUPO!");
                            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "<null>", e);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(GrupoDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jB_excluirActionPerformed

    private void jB_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarActionPerformed
        if (grupo != null) {
            grupo.setDescricao(jTF_descricao.getText());
            grupo.setData_edicao(new Date());
            grupo.setVasilhames(jCB_vasilhames.isSelected());
            grupo.setId_usuario_edicao(1);
            try {
                Fachada.getInstancia().editarGrupo(grupo);
                JOptionPane.showMessageDialog(null, "GRUPO EDITADO COM SUCESSO!",
                        "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE, null);
                limpar();
                listarGrupo();
                jTP_grupo.remove(1);
                jTP_grupo.setSelectedIndex(0);
                grupo = null;
            } catch (HeadlessException e) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "<null>", e);
                JOptionPane.showMessageDialog(null, "NÃO FOI POSSIVEL EDITAR O GRUPO!",
                        "Alerta do Sistema", JOptionPane.ERROR_MESSAGE, null);
            } catch (SQLException ex) {
                Logger.getLogger(GrupoDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jB_editarActionPerformed

    private void jT_grupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_grupoKeyPressed
        try {
            int id = (Integer) jT_grupo.getModel().getValueAt(jT_grupo.getSelectedRow(), 0);
            ArrayList lista = Fachada.getInstancia().consultarGrupo("select * from grupo where id = " + id + " and not excluido");
            grupo = (Grupo) lista.get(0);
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (consultar) {
                    dispose();
                } else {
                    grupoSelecionado();
                    botaoSalvar(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrupoDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jT_grupoKeyPressed

    private void jB_excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_excluir1ActionPerformed
        jTP_grupo.remove(1);
        jTP_grupo.setSelectedIndex(0);
    }//GEN-LAST:event_jB_excluir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupoDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                GrupoDialogGUI dialog = new GrupoDialogGUI(new javax.swing.JFrame(), true, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_OK;
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_editar;
    private javax.swing.JButton jB_excluir;
    private javax.swing.JButton jB_excluir1;
    private javax.swing.JButton jB_novo;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JCheckBox jCB_vasilhames;
    private javax.swing.JLabel jL_codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jP_cadastrar;
    private javax.swing.JPanel jP_consultar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_descricao;
    private org.jdesktop.swingx.JXSearchField jTF_pesquisar;
    private javax.swing.JTabbedPane jTP_grupo;
    private javax.swing.JTable jT_grupo;
    // End of variables declaration//GEN-END:variables

    public void limparTabela() {
        DefaultTableModel tableData = (DefaultTableModel) jT_grupo.getModel();
        tableData.setRowCount(0);
        jT_grupo.setModel(tableData);
        jTF_pesquisar.requestFocus();
    }

    public final void listarGrupo() {
        try {
            limparTabela();
            int i = 0;
            ArrayList lista = Fachada.getInstancia().consultarGrupo("select * from grupo where not excluido");
            DefaultTableModel dtm = (DefaultTableModel) jT_grupo.getModel();
            while (i < lista.size()) {
                Grupo gTemp = (Grupo) lista.get(i);
                dtm.addRow(new Object[]{gTemp.getId(), gTemp.getDescricao()});
                i++;
            }
            jL_codigo.setText(String.valueOf(Fachada.getInstancia().retornoAutoIncrementGrupo()));
        } catch (SQLException ex) {
            Logger.getLogger(GrupoDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public final void botaoSalvar(boolean b) {
        jB_salvar.setEnabled(b);
    }

    private void grupoSelecionado() {
        jB_editar.setEnabled(true);
        jB_excluir.setEnabled(true);
        int i = jT_grupo.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "NENHUM GRUPO SELECIONADO!",
                    "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE, null);
        } else {
            jTP_grupo.add("Cadastrar", jP_cadastrar);
            jTF_descricao.setText(grupo.getDescricao());
            jCB_vasilhames.setSelected(grupo.isVasilhames());
            jL_codigo.setText(String.valueOf(grupo.getId()));
            jTP_grupo.setSelectedIndex(1);
            jP_cadastrar.hasFocus();
        }
    }

    public void limpar() {
        try {
            jTF_descricao.setText("");
            jL_codigo.setText(String.valueOf(Fachada.getInstancia().retornoAutoIncrementGrupo()));
            jCB_vasilhames.setSelected(false);
        } catch (SQLException ex) {
            Logger.getLogger(GrupoDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void salvar() {
        grupo = new Grupo();
        grupo.setDescricao(jTF_descricao.getText().toUpperCase());
        grupo.setVasilhames(jCB_vasilhames.isSelected());
        grupo.setData_insercao(new Date());
        grupo.setId_usuario_insercao(1);
        try {
            Fachada.getInstancia().incluirGrupo(grupo);
            if (consultar) {
                ArrayList lista = Fachada.getInstancia().consultarGrupo("select * from grupo where id = " + grupo.getId() + " and not excluido");
                grupo = (Grupo) lista.get(0);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "GRUPO SALVO COM SUCESSO!",
                        "Alerta do Sistema", JOptionPane.INFORMATION_MESSAGE, null);
                jTF_descricao.setText("");
                listarGrupo();
                jTP_grupo.remove(1);
                jTP_grupo.setSelectedIndex(0);
            }
        } catch (HeadlessException e) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "<null>", e);
        } catch (SQLException ex) {
            Logger.getLogger(GrupoDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void pesquisar() {
        try {
            String pesquisa = jTF_pesquisar.getText().isEmpty() ? "%" : jTF_pesquisar.getText();
            ArrayList<Grupo> lista = Fachada.getInstancia().consultarGrupo("select * from grupo where id like '" + pesquisa + "' OR descricao like '%" + pesquisa + "%'");
            DefaultTableModel dtm = (DefaultTableModel) jT_grupo.getModel();
            limparTabela();
            for (Grupo gTemp : lista) {
                dtm.addRow(new Object[]{gTemp.getId(), gTemp.getDescricao()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrupoDialogGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void insereProdutoRapido() {
        limpar();
        jB_editar.setEnabled(false);
        jB_excluir.setEnabled(false);
        jB_salvar.setEnabled(true);
        jTP_grupo.setSelectedIndex(1);
    }

    public Grupo getGrupo() {
        return grupo;
    }
}
