/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dados.ConectaBDProduto;
import Negocios.Fachada;
import Negocios.Produto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXSearchField;

/**
 *
 * @author Neto
 */
public class ListaProdutoVasilhameDialog extends javax.swing.JDialog {

    /**
     * Creates new form ListaProdutoVasilhameDialog
     *
     * @param parent
     * @param modal
     */
    private Produto produto;

    public ListaProdutoVasilhameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            pesquisar();
        } catch (SQLException ex) {
            Logger.getLogger(ListaProdutoVasilhameDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTF_pesquisar.setSearchMode(JXSearchField.SearchMode.REGULAR);
        jTF_pesquisar.addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    try {
                        pesquisar();
                    } catch (SQLException ex) {
                        Logger.getLogger(ListaProdutoVasilhameDialog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    if (jT_produto.getRowCount() > 0) {
                        jT_produto.addRowSelectionInterval(0, 0);
                        jT_produto.requestFocus();
                    }
                }
            }
        });

        jTF_pesquisar.setFindAction(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    pesquisar();
                } catch (SQLException ex) {
                    Logger.getLogger(ListaProdutoVasilhameDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTF_pesquisar = new org.jdesktop.swingx.JXSearchField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_produto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Vasilhames");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTF_pesquisar.setPrompt("Buscar");

        jT_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Código", "Descrição", "Qtd estoque", "Valor Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_produto.getTableHeader().setReorderingAllowed(false);
        jT_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_produtoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_produto);
        if (jT_produto.getColumnModel().getColumnCount() > 0) {
            jT_produto.getColumnModel().getColumn(0).setMinWidth(0);
            jT_produto.getColumnModel().getColumn(0).setPreferredWidth(0);
            jT_produto.getColumnModel().getColumn(0).setMaxWidth(0);
            jT_produto.getColumnModel().getColumn(1).setPreferredWidth(80);
            jT_produto.getColumnModel().getColumn(2).setPreferredWidth(250);
            jT_produto.getColumnModel().getColumn(3).setPreferredWidth(100);
            jT_produto.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTF_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_produtoMouseClicked
        if (evt.getClickCount() == 2) {
            dispose();
        }
    }//GEN-LAST:event_jT_produtoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProdutoVasilhameDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ListaProdutoVasilhameDialog dialog = new ListaProdutoVasilhameDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXSearchField jTF_pesquisar;
    private javax.swing.JTable jT_produto;
    // End of variables declaration//GEN-END:variables

    private void pesquisar() throws SQLException {
        DefaultTableModel dtm = (DefaultTableModel) jT_produto.getModel();
        dtm.setRowCount(0);
        ArrayList<Produto> lista = ConectaBDProduto.getInstance().consultarProduto(
                "select p.* from produto p INNER JOIN grupo g ON p.id_grupo = g.id and g.vasilhame where "
                + "not g.excluido and not p.excluido and p.descricao like '%" + jTF_pesquisar.getText().trim() + "%' "
                + "OR p.codigo like '" + jTF_pesquisar.getText() + "'");
        for (Produto p : lista) {
            dtm.addRow(new Object[]{p.getId(), p.getCodigo(), p.getDescricao(), p.getQtd_estoque(), p.getValor_venda()});
        }
    }

    public Produto getProduto() {
        try {
            int row = jT_produto.getSelectedRow();
            if (row > -1) {
                int idProduto = (Integer) jT_produto.getModel().getValueAt(row, 0);
                ArrayList<Produto> lista = ConectaBDProduto.getInstance().consultarProduto(
                        "select * from produto p where p.id = " + idProduto);
                if (!lista.isEmpty()) {
                    return produto = lista.get(0);
                } else {
                    return null;
                }
            } else {
                return null;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ListaProdutoVasilhameDialog.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
}
