/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dados.ConectaBDProduto;
import sistema.gas.unidadeProduto.dados.ConectaBDUnidadeProduto;
import Negocios.Fachada;
import Negocios.Grupo;
import Negocios.Produto;
import Utilitarios.ClasseUtilitaria;
import sistema.gas.unidadeProduto.negocios.UnidadeProduto;
import Utilitarios.Dir;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static sistema.gas.SISTEMA_GAS._FuncionarioLogado;

/**
 *
 * @author Neto
 */
public class ProdutoDialog extends javax.swing.JDialog {

    /**
     * Creates new form ProdutoDialog
     *
     * @param parent
     * @param modal
     */
    private Produto produto;
    private Grupo grupo;
    private final boolean consultar;

    public ProdutoDialog(java.awt.Frame parent, boolean modal, boolean consultar) {
        super(parent, modal);
        initComponents();
        this.consultar = consultar;
        getTipoSistema(Dir.KEY_TIPO_SISTEMA);
        configuracoesIniciais();
        try {
            pesquisar();
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoDialog.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao consultar produtos. Erro: " + ex.getMessage());
        }
        actionPesquisar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_filtro = new javax.swing.ButtonGroup();
        jTP_produto = new javax.swing.JTabbedPane();
        jP_consultar = new javax.swing.JPanel();
        jRB_codigo = new javax.swing.JRadioButton();
        jRB_descricao = new javax.swing.JRadioButton();
        jTF_pesquisar = new org.jdesktop.swingx.JXSearchField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_consulta = new javax.swing.JTable();
        jB_novo = new javax.swing.JButton();
        jB_abrir = new javax.swing.JButton();
        jB_fechar = new javax.swing.JButton();
        jP_cadastrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTF_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_descricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_data_cadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_qtd_estoque = new javax.swing.JTextField();
        jTF_qtd_estoque_avaria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTF_valor_venda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTF_cod_grupo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTF_desc_grupo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTF_qtd_vasilhame = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTF_cod_vasilhame = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTF_desc_vasilhame = new javax.swing.JTextField();
        jB_salvar = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jB_excluir = new javax.swing.JButton();
        jB_voltar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTF_valor_compra = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTF_lucro = new javax.swing.JTextField();
        jTF_lucro_real = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTF_cod_fornecedor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTF_nome_fornecedor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jcbUnidade = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTP_produto.setEnabled(false);

        buttonGroup_filtro.add(jRB_codigo);
        jRB_codigo.setSelected(true);
        jRB_codigo.setText("Código");
        jRB_codigo.setFocusable(false);

        buttonGroup_filtro.add(jRB_descricao);
        jRB_descricao.setText("Descrição");
        jRB_descricao.setFocusable(false);

        jTF_pesquisar.setPrompt("Buscar");

        jT_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Código", "Descrição", "Unidade", "Qtd est.", "Qtd. est. Avaria", "Valor Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_consulta.getTableHeader().setReorderingAllowed(false);
        jT_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_consultaMouseClicked(evt);
            }
        });
        jT_consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_consultaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jT_consulta);
        if (jT_consulta.getColumnModel().getColumnCount() > 0) {
            jT_consulta.getColumnModel().getColumn(0).setMinWidth(0);
            jT_consulta.getColumnModel().getColumn(0).setPreferredWidth(0);
            jT_consulta.getColumnModel().getColumn(0).setMaxWidth(0);
            jT_consulta.getColumnModel().getColumn(1).setPreferredWidth(80);
            jT_consulta.getColumnModel().getColumn(2).setPreferredWidth(300);
            jT_consulta.getColumnModel().getColumn(3).setPreferredWidth(50);
            jT_consulta.getColumnModel().getColumn(4).setPreferredWidth(80);
            jT_consulta.getColumnModel().getColumn(5).setPreferredWidth(100);
            jT_consulta.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        jB_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adiciona.png"))); // NOI18N
        jB_novo.setText("Novo");
        jB_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_novoActionPerformed(evt);
            }
        });

        jB_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jB_abrir.setText("Abrir");
        jB_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_abrirActionPerformed(evt);
            }
        });

        jB_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jB_fechar.setText("Fechar");
        jB_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_consultarLayout = new javax.swing.GroupLayout(jP_consultar);
        jP_consultar.setLayout(jP_consultarLayout);
        jP_consultarLayout.setHorizontalGroup(
            jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_consultarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                    .addGroup(jP_consultarLayout.createSequentialGroup()
                        .addGroup(jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRB_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRB_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
            .addGroup(jP_consultarLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jB_novo)
                .addGap(0, 0, 0)
                .addComponent(jB_abrir)
                .addGap(0, 0, 0)
                .addComponent(jB_fechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_consultarLayout.setVerticalGroup(
            jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_consultarLayout.createSequentialGroup()
                .addGroup(jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_consultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRB_codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_descricao))
                    .addGroup(jP_consultarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTF_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_novo)
                    .addComponent(jB_abrir)
                    .addComponent(jB_fechar))
                .addGap(5, 5, 5))
        );

        jTP_produto.addTab("Consultar", jP_consultar);

        jLabel1.setText("Código:");

        jTF_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_codigoKeyPressed(evt);
            }
        });

        jLabel2.setText("Descrição:");

        jTF_descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_descricaoKeyPressed(evt);
            }
        });

        jLabel3.setText("Data Cadastro:");

        jTF_data_cadastro.setEnabled(false);

        jLabel4.setText("Qtd. estoque:");

        jTF_qtd_estoque.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_qtd_estoque.setText("0,0000");
        jTF_qtd_estoque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGainedSelectAll(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FocusLostFormaterDecimal(evt);
            }
        });
        jTF_qtd_estoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_qtd_estoqueKeyPressed(evt);
            }
        });

        jTF_qtd_estoque_avaria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_qtd_estoque_avaria.setText("0,0000");
        jTF_qtd_estoque_avaria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGainedSelectAll(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FocusLostFormaterDecimal(evt);
            }
        });
        jTF_qtd_estoque_avaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_qtd_estoque_avariaKeyPressed(evt);
            }
        });

        jLabel5.setText("Qtd. estoque avaria:");

        jLabel6.setText("Valor Venda:");

        jTF_valor_venda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_valor_venda.setText("0,0000");
        jTF_valor_venda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGainedSelectAll(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_valor_vendaFocusLost(evt);
            }
        });
        jTF_valor_venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_valor_vendaKeyPressed(evt);
            }
        });

        jLabel7.setText("Grupo:");

        jTF_cod_grupo.setToolTipText("Pressione F1 para buscar o grupo");
        jTF_cod_grupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_cod_grupoKeyPressed(evt);
            }
        });

        jLabel8.setText("-");

        jTF_desc_grupo.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Vasilhame");

        jLabel10.setText("Quantidade:");

        jTF_qtd_vasilhame.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_qtd_vasilhame.setText("0,0000");
        jTF_qtd_vasilhame.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGainedSelectAll(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FocusLostFormaterDecimal(evt);
            }
        });
        jTF_qtd_vasilhame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_qtd_vasilhameKeyPressed(evt);
            }
        });

        jLabel11.setText("Vasilhame:");

        jTF_cod_vasilhame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_cod_vasilhameKeyPressed(evt);
            }
        });

        jLabel12.setText("-");

        jTF_desc_vasilhame.setEnabled(false);

        jB_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk.png"))); // NOI18N
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jB_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wand.png"))); // NOI18N
        jB_editar.setText("Editar");
        jB_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarActionPerformed(evt);
            }
        });

        jB_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bin_closed.png"))); // NOI18N
        jB_excluir.setText("Excluir");
        jB_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_excluirActionPerformed(evt);
            }
        });

        jB_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar[1].jpg"))); // NOI18N
        jB_voltar.setText("Voltar");
        jB_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarActionPerformed(evt);
            }
        });

        jLabel13.setText("Valor compra:");

        jTF_valor_compra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_valor_compra.setText("0,0000");
        jTF_valor_compra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGainedSelectAll(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FocusLostFormaterDecimal(evt);
            }
        });
        jTF_valor_compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_valor_compraKeyPressed(evt);
            }
        });

        jLabel14.setText("Lucro:");

        jTF_lucro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_lucro.setText("0,0000");
        jTF_lucro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGainedSelectAll(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_lucroFocusLost(evt);
            }
        });
        jTF_lucro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_lucroKeyPressed(evt);
            }
        });

        jTF_lucro_real.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF_lucro_real.setText("0,0000");
        jTF_lucro_real.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGainedSelectAll(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_lucro_realFocusLost(evt);
            }
        });
        jTF_lucro_real.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_lucro_realKeyPressed(evt);
            }
        });

        jLabel15.setText("%");

        jLabel17.setText("$");

        jLabel16.setText("Fornecedor:");

        jTF_cod_fornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_cod_fornecedorKeyPressed(evt);
            }
        });

        jLabel18.setText("-");

        jTF_nome_fornecedor.setEditable(false);
        jTF_nome_fornecedor.setFocusable(false);

        jLabel19.setText("Unidade:");

        javax.swing.GroupLayout jP_cadastrarLayout = new javax.swing.GroupLayout(jP_cadastrar);
        jP_cadastrar.setLayout(jP_cadastrarLayout);
        jP_cadastrarLayout.setHorizontalGroup(
            jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jB_salvar)
                .addGap(0, 0, 0)
                .addComponent(jB_editar)
                .addGap(0, 0, 0)
                .addComponent(jB_excluir)
                .addGap(0, 0, 0)
                .addComponent(jB_voltar)
                .addContainerGap(199, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_cadastrarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_descricao)
                            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                                .addComponent(jTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_data_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                                .addComponent(jTF_cod_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_desc_grupo))))
                    .addGroup(jP_cadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTF_qtd_vasilhame)
                                    .addComponent(jTF_cod_vasilhame, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_desc_vasilhame))
                            .addComponent(jLabel9)))
                    .addGroup(jP_cadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTF_valor_compra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_qtd_estoque, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_cod_fornecedor)
                            .addComponent(jcbUnidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_cadastrarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_qtd_estoque_avaria, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_lucro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(3, 3, 3)
                                .addComponent(jTF_lucro_real, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_cadastrarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_nome_fornecedor)))))
                .addContainerGap())
        );

        jP_cadastrarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTF_lucro, jTF_lucro_real, jTF_valor_compra, jTF_valor_venda});

        jP_cadastrarLayout.setVerticalGroup(
            jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_data_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTF_cod_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTF_desc_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTF_cod_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTF_nome_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jcbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTF_qtd_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_qtd_estoque_avaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTF_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jTF_valor_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jTF_lucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel17)
                        .addComponent(jTF_lucro_real, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTF_qtd_vasilhame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTF_cod_vasilhame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTF_desc_vasilhame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jP_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_salvar)
                    .addComponent(jB_editar)
                    .addComponent(jB_excluir)
                    .addComponent(jB_voltar))
                .addGap(5, 5, 5))
        );

        jP_cadastrarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTF_lucro, jTF_lucro_real, jTF_valor_compra, jTF_valor_venda});

        jTP_produto.addTab("Cadastrar", jP_cadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTP_produto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTP_produto)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_novoActionPerformed
        produtoNovo();
    }//GEN-LAST:event_jB_novoActionPerformed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        try {
            if (contemCamposObrigatorios()) {
            } else {
                setarObjeto("S");
                ConectaBDProduto.getInstance().salvarProduto(produto);
                if (consultar) {
                    dispose();
                } else {
                    limparCampos();
                    pesquisar();
                    JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!", "ALERTA DO SISTEMA", JOptionPane.INFORMATION_MESSAGE);
                    jTP_produto.setSelectedIndex(0);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jB_salvarActionPerformed

    private void FocusGainedSelectAll(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FocusGainedSelectAll
        ((JTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_FocusGainedSelectAll

    private void jTF_cod_grupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_cod_grupoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && (!jTF_cod_grupo.getText().isEmpty())) {
            try {
                ArrayList<Grupo> listaGrupo = Fachada.getInstancia().consultarGrupo("select * from grupo where id = " + jTF_cod_grupo.getText().trim());
                if (!listaGrupo.isEmpty()) {
                    grupo = listaGrupo.get(0);
//                    liberarCamposVasilhames(grupo.isVasilhames());
                    jTF_cod_grupo.setText(String.valueOf(grupo.getId()));
                    jTF_desc_grupo.setText(grupo.getDescricao());

                    jTF_qtd_estoque.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            GrupoDialogGUI grupoDialogGUI = new GrupoDialogGUI(null, true, true);
            grupoDialogGUI.setLocationRelativeTo(null);
            grupoDialogGUI.setVisible(true);
            grupo = grupoDialogGUI.getGrupo();
            if (grupo != null) {
//                liberarCamposVasilhames(grupo.isVasilhames());
                jTF_cod_grupo.setText(String.valueOf(grupo.getId()));
                jTF_desc_grupo.setText(grupo.getDescricao());

                jTF_qtd_estoque.requestFocus();
            }
        }
    }//GEN-LAST:event_jTF_cod_grupoKeyPressed

    private void jTF_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_codigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_descricao.requestFocus();
        }
    }//GEN-LAST:event_jTF_codigoKeyPressed

    private void jTF_descricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_descricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_cod_grupo.requestFocus();
        }
    }//GEN-LAST:event_jTF_descricaoKeyPressed

    private void jTF_qtd_estoqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_qtd_estoqueKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_qtd_estoque_avaria.requestFocus();
        }
    }//GEN-LAST:event_jTF_qtd_estoqueKeyPressed

    private void jTF_qtd_estoque_avariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_qtd_estoque_avariaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_valor_compra.requestFocus();
        }
    }//GEN-LAST:event_jTF_qtd_estoque_avariaKeyPressed

    private void jTF_valor_vendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_valor_vendaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_qtd_vasilhame.requestFocus();
        }
    }//GEN-LAST:event_jTF_valor_vendaKeyPressed

    private void jTF_qtd_vasilhameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_qtd_vasilhameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_cod_vasilhame.requestFocus();
        }
    }//GEN-LAST:event_jTF_qtd_vasilhameKeyPressed

    private void jTF_cod_vasilhameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_cod_vasilhameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            ListaProdutoVasilhameDialog dialog = new ListaProdutoVasilhameDialog(null, true);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
            Produto produtoVasilhame = dialog.getProduto();
            if (produtoVasilhame != null) {
                jTF_cod_vasilhame.setText(produtoVasilhame.getId().toString());
                jTF_desc_vasilhame.setText(produtoVasilhame.getDescricao());
            }
        }
    }//GEN-LAST:event_jTF_cod_vasilhameKeyPressed

    private void jB_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_abrirActionPerformed
        limparCampos();
        produtoSelecionado();
    }//GEN-LAST:event_jB_abrirActionPerformed

    private void jT_consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_consultaMouseClicked
        if (evt.getClickCount() == 2) {
            limparCampos();
            produtoSelecionado();
        }
    }//GEN-LAST:event_jT_consultaMouseClicked

    private void jB_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarActionPerformed
        try {
            limparCampos();
            pesquisar();
            jTP_produto.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoDialog.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Problemas ao salvar!", "ALERTA DO SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jB_voltarActionPerformed

    private void jB_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarActionPerformed
        try {
            if (contemCamposObrigatorios()) {
            } else {
                setarObjeto("E");
                ConectaBDProduto.getInstance().salvarProduto(produto);
                if (consultar) {
                    dispose();
                } else {
                    limparCampos();
                    pesquisar();
                    JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!", "ALERTA DO SISTEMA", JOptionPane.INFORMATION_MESSAGE);
                    jTP_produto.setSelectedIndex(0);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Problemas ao salvar!", "ALERTA DO SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jB_editarActionPerformed

    private void jB_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_excluirActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o produto selecionado?", "PERGUNTA DO SISTEMA", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                produto.setData_exclusao(new Date());
                produto.setId_usuario_exclusao(_FuncionarioLogado.getId());
                ConectaBDProduto.getInstance().excluirProduto(produto);
                limparCampos();
                pesquisar();
                JOptionPane.showMessageDialog(rootPane, "Excluído com sucesso!", "ALERTA DO SISTEMA", JOptionPane.INFORMATION_MESSAGE);
                jTP_produto.setSelectedIndex(0);
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jB_excluirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (jTP_produto.getSelectedIndex() == 1) {
            try {
                limparCampos();
                pesquisar();
                jTP_produto.setSelectedIndex(0);
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoDialog.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Problemas ao salvar!", "ALERTA DO SISTEMA", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            produto = null;
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jB_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_fecharActionPerformed
        produto = null;
        dispose();
    }//GEN-LAST:event_jB_fecharActionPerformed

    private void jTF_lucro_realFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_lucro_realFocusLost
        FocusLostFormaterDecimal(evt);
        BigDecimal valorCompra = ClasseUtilitaria.parseToBig(jTF_valor_compra.getText().isEmpty() ? "0" : jTF_valor_compra.getText());
        BigDecimal valorLucroReal = ClasseUtilitaria.parseToBig(jTF_lucro_real.getText());
        BigDecimal valorVenda = valorCompra.add(valorLucroReal);
        if (valorCompra.compareTo(BigDecimal.ZERO) != 0) {
            BigDecimal valorLucroPorcentagem = ((valorVenda.subtract(valorCompra)).divide(valorCompra, 4, RoundingMode.HALF_DOWN)).multiply(ClasseUtilitaria.parseToBig("100"));
            jTF_valor_venda.setText(ClasseUtilitaria.fmtBig(valorVenda, 2));
            jTF_lucro.setText(ClasseUtilitaria.fmtBig(valorLucroPorcentagem, 4));
        }
    }//GEN-LAST:event_jTF_lucro_realFocusLost

    private void jTF_valor_vendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_valor_vendaFocusLost
        FocusLostFormaterDecimal(evt);
        calculaValorVendaInverso();
    }//GEN-LAST:event_jTF_valor_vendaFocusLost

    private void jTF_valor_compraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_valor_compraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_lucro.requestFocus();
        }
    }//GEN-LAST:event_jTF_valor_compraKeyPressed

    private void jTF_lucroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_lucroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_lucro_real.requestFocus();
        }
    }//GEN-LAST:event_jTF_lucroKeyPressed

    private void jTF_lucro_realKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_lucro_realKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTF_valor_venda.requestFocus();
        }
    }//GEN-LAST:event_jTF_lucro_realKeyPressed

    private void jT_consultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_consultaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limparCampos();
            produtoSelecionado();
        }
    }//GEN-LAST:event_jT_consultaKeyPressed

    private void FocusLostFormaterDecimal(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FocusLostFormaterDecimal
        int scale = ((evt.getComponent() == jTF_qtd_estoque || evt.getComponent() == jTF_qtd_estoque_avaria || evt.getComponent() == jTF_qtd_vasilhame || evt.getComponent() == jTF_lucro) ? 4 : 2);
        ((JTextField) evt.getComponent()).setText(ClasseUtilitaria.fmtBig(ClasseUtilitaria.parseToBig(((JTextField) evt.getComponent()).getText()), scale));
    }//GEN-LAST:event_FocusLostFormaterDecimal

    private void jTF_cod_fornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_cod_fornecedorKeyPressed

    }//GEN-LAST:event_jTF_cod_fornecedorKeyPressed

    private void jTF_lucroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_lucroFocusLost
        FocusLostFormaterDecimal(evt);
        BigDecimal valorCompra = ClasseUtilitaria.parseToBig(jTF_valor_compra.getText().isEmpty() ? "0" : jTF_valor_compra.getText());
        BigDecimal pLucro = ClasseUtilitaria.parseToBig(jTF_lucro.getText());
        BigDecimal vLucro = valorCompra.multiply(pLucro.divide(ClasseUtilitaria.parseToBig("100"), 6, RoundingMode.HALF_DOWN));
        if (valorCompra.compareTo(BigDecimal.ZERO) != 0) {
            jTF_valor_venda.setText(ClasseUtilitaria.fmtBig(valorCompra.add(vLucro), 2));
            jTF_lucro_real.setText(ClasseUtilitaria.fmtBig(vLucro, 2));
        }
    }//GEN-LAST:event_jTF_lucroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ProdutoDialog dialog = new ProdutoDialog(new javax.swing.JFrame(), true, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_filtro;
    private javax.swing.JButton jB_abrir;
    private javax.swing.JButton jB_editar;
    private javax.swing.JButton jB_excluir;
    private javax.swing.JButton jB_fechar;
    private javax.swing.JButton jB_novo;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP_cadastrar;
    private javax.swing.JPanel jP_consultar;
    private javax.swing.JRadioButton jRB_codigo;
    private javax.swing.JRadioButton jRB_descricao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTF_cod_fornecedor;
    private javax.swing.JTextField jTF_cod_grupo;
    private javax.swing.JTextField jTF_cod_vasilhame;
    private javax.swing.JTextField jTF_codigo;
    private javax.swing.JTextField jTF_data_cadastro;
    private javax.swing.JTextField jTF_desc_grupo;
    private javax.swing.JTextField jTF_desc_vasilhame;
    private javax.swing.JTextField jTF_descricao;
    private javax.swing.JTextField jTF_lucro;
    private javax.swing.JTextField jTF_lucro_real;
    private javax.swing.JTextField jTF_nome_fornecedor;
    private org.jdesktop.swingx.JXSearchField jTF_pesquisar;
    private javax.swing.JTextField jTF_qtd_estoque;
    private javax.swing.JTextField jTF_qtd_estoque_avaria;
    private javax.swing.JTextField jTF_qtd_vasilhame;
    private javax.swing.JTextField jTF_valor_compra;
    private javax.swing.JTextField jTF_valor_venda;
    private javax.swing.JTabbedPane jTP_produto;
    private javax.swing.JTable jT_consulta;
    private javax.swing.JComboBox<UnidadeProduto> jcbUnidade;
    // End of variables declaration//GEN-END:variables

    private void produtoNovo() {
        produto = new Produto();
        limparCampos();
        jTP_produto.setSelectedIndex(1);
        botoes(true, false, false);
    }

    private void limparCampos() {
        jTF_cod_grupo.setText("");
        jTF_cod_vasilhame.setText("");
        jTF_codigo.setText("");
        jTF_data_cadastro.setText("");
        jTF_desc_grupo.setText("");
        jTF_desc_vasilhame.setText("");
        jTF_descricao.setText("");
        jTF_qtd_estoque.setText("0,0000");
        jTF_qtd_estoque_avaria.setText("0,0000");
        jTF_qtd_vasilhame.setText("0,0000");
        jTF_valor_compra.setText("0,0000");
        jTF_lucro.setText("0,0000");
        jTF_lucro_real.setText("0,00");
        jTF_valor_venda.setText("0,0000");

        jTF_data_cadastro.setText(new Produto().getDateFormat(new Date()));
    }

    private void botoes(boolean b, boolean b0, boolean b1) {
        jB_salvar.setEnabled(b);
        jB_editar.setEnabled(b0);
        jB_excluir.setEnabled(b1);
    }

    private void setarObjeto(String tipo) {
        produto.setCodigo(jTF_codigo.getText());
        produto.setDescricao(jTF_descricao.getText().toUpperCase().trim());
        if (tipo.equals("S")) {
            produto.setId(0);
            produto.setData_cadastro(new Date());
        } else {
            produto.setData_edicao(new Date());
        }
        produto.setGrupo(grupo);
        produto.setQtd_estoque(ClasseUtilitaria.parseToBig(jTF_qtd_estoque.getText()));
        produto.setQtd_estoque_avaria(ClasseUtilitaria.parseToBig(jTF_qtd_estoque_avaria.getText()));
        produto.setValor_compra(ClasseUtilitaria.parseToBig(jTF_valor_compra.getText()));
        produto.setLucro(ClasseUtilitaria.parseToBig(jTF_lucro.getText()));
        produto.setValor_venda(ClasseUtilitaria.parseToBig(jTF_valor_venda.getText()));
        produto.setQtd_vasilhame(ClasseUtilitaria.parseToBig(jTF_qtd_vasilhame.getText()));
        produto.setId_produto_vasilhame(jTF_cod_vasilhame.getText().isEmpty() ? null : Integer.parseInt(jTF_cod_vasilhame.getText()));
        produto.setId_usuario_insercao(_FuncionarioLogado.getId());
        produto.setId_usuario_edicao(_FuncionarioLogado.getId());
        produto.setUnidadeProduto((UnidadeProduto) jcbUnidade.getSelectedItem());
    }

    private void produtoSelecionado() {
        try {
            int row = jT_consulta.getSelectedRow();
            if (row > -1) {
                int idProduto = (Integer) jT_consulta.getModel().getValueAt(row, 0);
                ArrayList<Produto> lista = ConectaBDProduto.getInstance().consultarProduto("select * from produto where id = " + idProduto);
                produto = lista.get(0);
                if (consultar) {
                    dispose();
                } else {
                    grupo = produto.getGrupo();
                    jTF_data_cadastro.setText(produto.getDateFormat(produto.getData_cadastro()));
                    jTF_codigo.setText(produto.getCodigo());
                    jTF_descricao.setText(produto.getDescricao());
                    jcbUnidade.setSelectedItem(produto.getUnidadeProduto());
                    jTF_cod_grupo.setText(String.valueOf(produto.getGrupo().getId()));
                    jTF_desc_grupo.setText(produto.getGrupo().getDescricao());
                    jTF_qtd_estoque.setText(produto.getQtd_estoqueFMT());
                    jTF_qtd_estoque_avaria.setText(produto.getQtd_estoque_avariaFMT());
                    jTF_valor_venda.setText(produto.getValor_vendaFMT());
                    jTF_valor_compra.setText(produto.getValor_compraFMT());
                    jTF_lucro.setText(produto.getLucroFMT());
                    BigDecimal lucroReal = produto.getValor_venda().subtract(produto.getValor_compra());
                    jTF_lucro_real.setText(ClasseUtilitaria.fmtBig(lucroReal, 2));
                    jTF_qtd_vasilhame.setText(produto.getQtd_vasilhameFMT());
                    if (produto.getId_produto_vasilhame() != 0) {
                        ArrayList<Produto> listaProdutoVasilhame = ConectaBDProduto.getInstance().consultarProduto("select * from produto where id = " + produto.getId_produto_vasilhame());
                        jTF_cod_vasilhame.setText(listaProdutoVasilhame.get(0).getId().toString());
                        jTF_desc_vasilhame.setText(listaProdutoVasilhame.get(0).getDescricao());
                    } else {
                        jTF_cod_vasilhame.setText("");
                        jTF_desc_vasilhame.setText("");
                    }

                    jTP_produto.setSelectedIndex(1);
                    botoes(false, true, true);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nenhuma linha selecionada!", "ALERTA DO SISTEMA", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void pesquisar() throws SQLException {
        DefaultTableModel dtm = (DefaultTableModel) jT_consulta.getModel();
        dtm.setRowCount(0);
        jRB_codigo.setActionCommand("codigo");
        jRB_descricao.setActionCommand("descricao");
        String pesquisar = jTF_pesquisar.getText().isEmpty() ? "%" : jRB_codigo.isSelected() ? jTF_pesquisar.getText() : "%" + jTF_pesquisar.getText() + "%";
        ArrayList<Produto> lista = ConectaBDProduto.getInstance().consultarProduto(
                "select * from produto where not excluido and " + buttonGroup_filtro.getSelection().getActionCommand() + " like '" + pesquisar + "'");
        for (Produto p : lista) {
            dtm.addRow(new Object[]{
                p.getId(),
                p.getCodigo(),
                p.getDescricao(),
                (p.getUnidadeProduto() == null ? "INSERIR" : p.getUnidadeProduto().getNome()),
                p.getQtd_estoqueFMT(),
                p.getQtd_estoque_avariaFMT(),
                p.getValor_vendaFMT()
            });
        }
    }

    private void liberarCamposVasilhames(boolean vasilhames) {
        jTF_qtd_vasilhame.setEnabled(vasilhames);
        jTF_cod_vasilhame.setEnabled(vasilhames);
    }

    private boolean contemCamposObrigatorios() {
        boolean temCampoVazio = false;
        JTextField campos[] = {jTF_codigo, jTF_descricao, jTF_cod_grupo, jTF_desc_grupo, jTF_qtd_estoque, jTF_qtd_estoque_avaria, jTF_valor_venda, jTF_valor_compra, jTF_lucro};
        for (JTextField jTextField : campos) {
            if (jTextField.getText().isEmpty()) {
                jTextField.setBackground(Color.yellow);
                temCampoVazio = true;
            } else {
                jTextField.setBackground(Color.white);
            }
        }

        if (jcbUnidade.getSelectedItem() == null
                || ((UnidadeProduto) jcbUnidade.getSelectedItem()).getId() == 0) {
            temCampoVazio = true;
        }

        if (temCampoVazio) {
            JOptionPane.showMessageDialog(null, "CAMPO(s) OBRIGATÓRIO(s) EM BRANCO!", null, 2);
            return true;
        } else {
            return false;
        }
    }

    public Produto getProduto() {
        return produto;
    }

    private void calculaValorVenda(String lucro) {
        BigDecimal valorCompra = ClasseUtilitaria.parseToBig(jTF_valor_compra.getText().isEmpty() ? "0" : jTF_valor_compra.getText());
        BigDecimal valorLucroPorcentagem = ClasseUtilitaria.parseToBig(lucro.isEmpty() ? "0" : lucro);
        if (valorLucroPorcentagem.compareTo(BigDecimal.ZERO) != 0) {
            BigDecimal valorVenda = valorCompra.add(valorCompra.multiply(valorLucroPorcentagem.divide(ClasseUtilitaria.parseToBig("100"))));
            BigDecimal lucroReal = valorVenda.subtract(valorCompra);
            jTF_valor_venda.setText(valorVenda.setScale(2, RoundingMode.HALF_DOWN).toString());
            jTF_lucro_real.setText(lucroReal.setScale(2, RoundingMode.HALF_DOWN).toString());
        }
    }

    private void calculaValorVendaInverso() {
        BigDecimal valorCompra = ClasseUtilitaria.parseToBig(jTF_valor_compra.getText().isEmpty() ? "0" : jTF_valor_compra.getText());
        BigDecimal valorVenda = ClasseUtilitaria.parseToBig(jTF_valor_venda.getText().isEmpty() ? "0" : jTF_valor_venda.getText());
        if (valorCompra.compareTo(BigDecimal.ZERO) != 0) {
            BigDecimal valorLucroPorcentagem = ((valorVenda.subtract(valorCompra)).divide(valorCompra, 4, RoundingMode.HALF_DOWN)).multiply(ClasseUtilitaria.parseToBig("100"));
            BigDecimal valorLucroReal = (valorVenda.subtract(valorCompra));
            jTF_lucro.setText(ClasseUtilitaria.fmtBig(valorLucroPorcentagem, 4));
            jTF_lucro_real.setText(ClasseUtilitaria.fmtBig(valorLucroReal, 2));
        }
    }

    public final void getTipoSistema(String tipo) {
        switch (tipo) {
            case "G":
                jSeparator1.setVisible(true);
                jLabel9.setVisible(true);
                jLabel10.setVisible(true);
                jLabel11.setVisible(true);
                jTF_qtd_vasilhame.setVisible(true);
                jTF_cod_vasilhame.setVisible(true);
                jTF_desc_vasilhame.setVisible(true);
                jLabel12.setVisible(true);
                break;
            default:
                jSeparator1.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                jLabel11.setVisible(false);
                jTF_qtd_vasilhame.setVisible(false);
                jTF_cod_vasilhame.setVisible(false);
                jTF_desc_vasilhame.setVisible(false);
                jLabel12.setVisible(false);
        }
    }

    private void actionPesquisar() {
        jTF_pesquisar.addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    try {
                        pesquisar();
                    } catch (SQLException ex) {
                        Logger.getLogger(ListaProdutoVasilhameDialog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    if (jT_consulta.getRowCount() > 0) {
                        jT_consulta.addRowSelectionInterval(0, 0);
                        jT_consulta.requestFocus();
                    }
                }
            }
        });
    }

    private void configuracoesIniciais() {
        ArrayList<UnidadeProduto> listaUnidade = ConectaBDUnidadeProduto.getInstance().consultarPorTipo("nome", "%");
        jcbUnidade.removeAllItems();
        //Primeiro
        UnidadeProduto u = new UnidadeProduto();
        u.setId(0);
        u.setNome("Escolha...");
        jcbUnidade.addItem(u);
        for (UnidadeProduto up : listaUnidade) {
            jcbUnidade.addItem(up);
        }
    }
}
